using System;
using System.Collections.Generic;
using System.Drawing;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace TavernLens {
public static class Native {
 [DllImport("user32.dll")] public static extern bool SetWindowDisplayAffinity(IntPtr h,uint affinity);
 [DllImport("user32.dll")] public static extern bool SetLayeredWindowAttributes(IntPtr h,uint key,byte alpha,uint flags);
 [DllImport("user32.dll")] public static extern bool GetLayeredWindowAttributes(IntPtr h,out uint key,out byte alpha,out uint flags);
 [StructLayout(LayoutKind.Sequential)] public struct Rect {public int Left,Top,Right,Bottom;}
 [DllImport("user32.dll")] public static extern bool GetClientRect(IntPtr h,out Rect r);
 [DllImport("user32.dll")] public static extern bool ClientToScreen(IntPtr h,ref Point p);
 [DllImport("user32.dll")] public static extern bool IsIconic(IntPtr h);
 [DllImport("user32.dll")] public static extern IntPtr GetForegroundWindow();
 [DllImport("user32.dll")] public static extern int GetWindowLong(IntPtr h,int i);
 [DllImport("user32.dll")] public static extern int SetWindowLong(IntPtr h,int i,int v);
 [DllImport("user32.dll")] public static extern bool SetWindowPos(IntPtr h,IntPtr after,int x,int y,int w,int height,uint flags);
 [DllImport("user32.dll")] public static extern bool RegisterHotKey(IntPtr h,int id,uint mods,uint key);
 [DllImport("user32.dll")] public static extern bool UnregisterHotKey(IntPtr h,int id);
 [DllImport("user32.dll")] public static extern bool SetProcessDPIAware();
 [DllImport("user32.dll")] static extern uint GetWindowThreadProcessId(IntPtr h,out uint pid); public static bool IsOurWindow(IntPtr h){uint pid;GetWindowThreadProcessId(h,out pid);return pid==(uint)Process.GetCurrentProcess().Id;}
 public static Rectangle ClientBounds(IntPtr h){Rect r;Point p=new Point();if(!GetClientRect(h,out r)||!ClientToScreen(h,ref p))return Rectangle.Empty;return new Rectangle(p.X,p.Y,r.Right-r.Left,r.Bottom-r.Top);}
}
public static class Theme {
 public static Color Bg=Color.FromArgb(17,22,30),Panel=Color.FromArgb(26,33,44),Ink=Color.FromArgb(239,238,235),Muted=Color.FromArgb(157,161,175),Gold=Color.FromArgb(222,182,116),Green=Color.FromArgb(115,211,176);
 public static Font Font(float size=10,bool bold=false){return new Font("Segoe UI",size,bold?FontStyle.Bold:FontStyle.Regular);}
 public static Label Label(string text,int x,int y,int w,int h,float size=10,Color? color=null){return new Label{Text=text,Bounds=new Rectangle(x,y,w,h),Font=Font(size),ForeColor=color??Ink,BackColor=Color.Transparent};}
 public static Button Button(string text,Action click){var b=new SoftButton{Text=text,AutoSize=true,Height=34,FlatStyle=FlatStyle.Flat,BackColor=Panel,ForeColor=Ink,Padding=new Padding(9,3,9,3),Font=Font(9),Margin=new Padding(0,0,8,0)};b.FlatAppearance.BorderColor=Color.FromArgb(65,78,96);b.Click+=(s,e)=>click();return b;}
 public static DataGridView Grid(){var g=new DataGridView{Dock=DockStyle.Fill,BackgroundColor=Bg,BorderStyle=BorderStyle.None,ReadOnly=true,AllowUserToAddRows=false,AllowUserToDeleteRows=false,AllowUserToResizeRows=false,RowHeadersVisible=false,SelectionMode=DataGridViewSelectionMode.FullRowSelect,MultiSelect=false,AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill,EnableHeadersVisualStyles=false,GridColor=Panel,Font=Font(10),CellBorderStyle=DataGridViewCellBorderStyle.SingleHorizontal,ColumnHeadersBorderStyle=DataGridViewHeaderBorderStyle.None,RowTemplate={Height=48}};g.DefaultCellStyle.Padding=new Padding(9,0,5,0);g.AlternatingRowsDefaultCellStyle.BackColor=Color.FromArgb(21,28,38);g.DefaultCellStyle.BackColor=Bg;g.DefaultCellStyle.ForeColor=Ink;g.DefaultCellStyle.SelectionBackColor=Color.FromArgb(48,57,68);g.DefaultCellStyle.SelectionForeColor=Ink;g.ColumnHeadersDefaultCellStyle.BackColor=Panel;g.ColumnHeadersDefaultCellStyle.ForeColor=Muted;g.ColumnHeadersDefaultCellStyle.Font=Font(9,true);g.ColumnHeadersHeight=43;g.Paint+=(s,e)=>{if(g.Rows.Count==0){using(var f=Font(13,true))TextRenderer.DrawText(e.Graphics,"Nothing to show yet",f,new Rectangle(20,95,g.Width-40,30),Muted,TextFormatFlags.HorizontalCenter);using(var f=Font(9))TextRenderer.DrawText(e.Graphics,"Data appears here as you play or change your filters.",f,new Rectangle(20,130,g.Width-40,48),Muted,TextFormatFlags.HorizontalCenter|TextFormatFlags.WordBreak);}};return g;}
 public static void Columns(DataGridView g,params string[] names){foreach(string name in names)g.Columns.Add(name,name);}
 public static void Link(string url){Uri u;if(Uri.TryCreate(url,UriKind.Absolute,out u)&&u.Scheme=="https")Process.Start(new ProcessStartInfo(url){UseShellExecute=true});}
}
public class Article : ScrollableControl {
 public Article(){AutoScroll=true;DoubleBuffered=true;Padding=new Padding(24);}
 protected override void OnTextChanged(EventArgs e){base.OnTextChanged(e);AutoScrollPosition=Point.Empty;Invalidate();}
 protected override void OnResize(EventArgs e){base.OnResize(e);Invalidate();}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);var g=e.Graphics;g.TextRenderingHint=System.Drawing.Text.TextRenderingHint.ClearTypeGridFit;int y=16;int width=Math.Max(100,ClientSize.Width-46);using(var body=Theme.Font(10.5f))using(var heading=Theme.Font(11,true))foreach(string raw in Text.Split('\n')){string line=raw.TrimEnd('\r');bool isHeading=line.Length>0&&line.Length<80&&line==line.ToUpperInvariant()&&line.Any(Char.IsLetter);var f=isHeading?heading:body;int h=line.Length==0?13:(int)Math.Ceiling(g.MeasureString(line,f,width).Height)+7;using(var b=new SolidBrush(isHeading?Theme.Gold:Theme.Ink))g.DrawString(line,f,b,new RectangleF(16,y+AutoScrollPosition.Y,width,h));y+=h;}AutoScrollMinSize=new Size(0,y+20);}
}
public class Main : Form {
 public Settings Settings=Store.Read("settings.json",new Settings());public Catalog Catalog=new Catalog();public MatchState State=new MatchState();public Overlay Overlay;public CombatRunner Combat=new CombatRunner();bool preview;public bool Previewing {get{return preview;}}public SceneState Scenes=new SceneState();public RatingReader Rating;public SessionData Session=Store.Read("session.json",new SessionData());readonly Tail sceneTail=new Tail();LiveReader reader;
 readonly TabControl tabs=new TabControl();readonly Label connection=new Label(),fresh=new Label(),liveTitle=new Label(),statsTitle=new Label();
 readonly DataGridView board=Theme.Grid(),lobby=Theme.Grid(),heroes=Theme.Grid(),comps=Theme.Grid(),cards=Theme.Grid(),historyGrid=Theme.Grid();
 CorePreview corePreview;readonly TextBox heroSearch=new TextBox(),cardSearch=new TextBox(),compSearch=new TextBox();readonly Article details=new Article(),sources=new Article();
 readonly ComboBox tribe=new DarkCombo(),kind=new DarkCombo();readonly List<MatchRecord> history;readonly Tail tail=new Tail();readonly Timer timer=new Timer();
 NotifyIcon tray;string logPath="",error="",selectedComp="";DateTime lastDiscover=DateTime.MinValue,lastUpdate=DateTime.MinValue,logCreated=DateTime.MinValue;bool updating,closing,importing;int renders;string liveSignature="";
 public Main(){Icon=BrandAssets.AppIcon;Text="TavernLens · Battlegrounds companion";Size=new Size(1320,860);MinimumSize=new Size(1180,740);StartPosition=FormStartPosition.CenterScreen;BackColor=Theme.Bg;ForeColor=Theme.Ink;Font=Theme.Font();history=Store.Read("history.json",new List<MatchRecord>());State.OnComplete=Record;State.OnCombat=OnCombat;
  var header=new BrandHeader();header.Controls.Add(Theme.Label("TavernLens",86,25,280,34,23,Theme.Ink));header.Controls.Add(Theme.Label("A BETTER VIEW OF THE BATTLEGROUNDS",89,65,335,20,8,Theme.Muted));
  Catalog.Duos=Settings.DataMode=="Duos";Session=Store.Read(Catalog.Duos?"session-duos.json":"session.json",new SessionData());
  connection.SetBounds(490,29,720,24);connection.Font=Theme.Font(10,true);connection.BackColor=Color.Transparent;fresh.BackColor=Color.Transparent;connection.ForeColor=Theme.Green;fresh.SetBounds(490,57,720,48);fresh.Font=Theme.Font(9);fresh.ForeColor=Theme.Muted;header.Controls.Add(connection);header.Controls.Add(fresh);
  var footer=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=61,Padding=new Padding(22,13,0,0),BackColor=Theme.Panel};footer.Controls.Add(Theme.Button("Show / hide overlay",()=>{Settings.OverlayEnabled=!Settings.OverlayEnabled;SaveSettings();}));footer.Controls.Add(Theme.Button("Preview overlay",()=>{preview=!preview;if(preview){Settings.OverlayEnabled=true;Overlay.SetInteractive(true);Overlay.Follow(Handle,true);}else Overlay.Hide();}));footer.Controls.Add(Theme.Button("Refresh web data",()=>RefreshWeb()));footer.Controls.Add(Theme.Button("Minimize to tray",()=>Hide()));footer.Controls.Add(Theme.Button("Exit",()=>{closing=true;Close();}));
  tabs.Dock=DockStyle.Fill;tabs.Appearance=TabAppearance.FlatButtons;tabs.SizeMode=TabSizeMode.Fixed;tabs.ItemSize=new Size(0,1);tabs.Multiline=true;
  BuildLive();BuildHeroes();BuildComps();BuildCards();BuildStats();BuildSources();
  foreach(TabPage page in tabs.TabPages){var heading=new Label{BackColor=Color.Transparent,Text=page.Text,Dock=DockStyle.Top,Height=48,Font=Theme.Font(23,true),ForeColor=Theme.Ink};page.Controls.Add(heading);}
  Controls.Add(Design.MountDeck(tabs));Controls.Add(new NavigationRail(tabs));Controls.Add(header);Controls.Add(footer);Design.StyleTree(this);

  if(Session.Games.Count==0)Session.StartRating=Session.CurrentRating;Rating=new RatingReader(this);Overlay=new Overlay(this);Overlay.CreateControl();RenderLive();
  tray=new NotifyIcon{Icon=BrandAssets.AppIcon,Text="TavernLens — Battlegrounds",Visible=true};var menu=new ContextMenuStrip();menu.Items.Add("Open dashboard",null,(s,e)=>ShowDashboard());menu.Items.Add("Toggle overlay",null,(s,e)=>{Settings.OverlayEnabled=!Settings.OverlayEnabled;SaveSettings();});menu.Items.Add("Exit",null,(s,e)=>{closing=true;Close();});tray.ContextMenuStrip=menu;tray.DoubleClick+=(s,e)=>ShowDashboard();
  Shown+=(s,e)=>{bool ok=Native.RegisterHotKey(Handle,1,0x4006,(uint)Keys.O)&Native.RegisterHotKey(Handle,2,0x4006,(uint)Keys.Space)&Native.RegisterHotKey(Handle,3,0x4006,(uint)Keys.D);if(!ok)error="Some hotkeys are used by another app; tray controls remain available.";ShowComp();fresh.Text=Catalog.Freshness;connection.Text="WAITING FOR HEARTHSTONE";};
  FormClosing+=(s,e)=>{if(!closing&&e.CloseReason==CloseReason.UserClosing){e.Cancel=true;Hide();return;}timer.Stop();Rating.Dispose();tail.Dispose();if(reader!=null)reader.Dispose();sceneTail.Dispose();Overlay.Close();tray.Dispose();for(int i=1;i<=3;i++)Native.UnregisterHotKey(Handle,i);};
  Populate();timer.Interval=500;timer.Tick+=(s,e)=>Tick();if(!Program.DiagnosticMode)timer.Start();
 }
 TabPage Page(string name){var p=new TavernPage(name){BackColor=Theme.Bg,ForeColor=Theme.Ink,Padding=new Padding(24)};tabs.TabPages.Add(p);return p;}
 Control Bar(string text){return new Label{Text=text,Dock=DockStyle.Top,Height=65,ForeColor=Theme.Muted,Font=Theme.Font(9.5f),Padding=new Padding(0,10,12,10)};}
 void BuildLive(){var p=Page("Live match");liveTitle.BackColor=Color.Transparent;liveTitle.Dock=DockStyle.Top;liveTitle.Height=76;liveTitle.Font=Theme.Font(15,true);liveTitle.ForeColor=Theme.Green;p.Controls.Add(liveTitle);var split=new SplitContainer{Dock=DockStyle.Fill,Orientation=Orientation.Vertical,BackColor=Theme.Bg,SplitterWidth=14};split.Size=new Size(1000,480);split.SplitterDistance=550;p.Controls.Add(split);split.BringToFront();Theme.Columns(board,"Position","Minion","Attack","Health","Keywords");Theme.Columns(lobby,"Hero","Tier","Health","Place");split.Panel1.Controls.Add(board);split.Panel1.Controls.Add(Bar("YOUR OBSERVED BOARD · combat buffs may be temporary"));split.Panel2.Controls.Add(lobby);split.Panel2.Controls.Add(Bar("LOBBY · last visible hero state"));}
 void SearchStyle(TextBox box){box.Width=260;box.BackColor=Theme.Panel;box.ForeColor=Theme.Ink;box.BorderStyle=BorderStyle.FixedSingle;box.Font=Theme.Font(11);box.Margin=new Padding(0,4,12,0);}
 void BuildHeroes(){var p=Page("Hero rankings");Theme.Columns(heroes,"Rank","Hero","Avg place","Pick %","Games");p.Controls.Add(heroes);var bar=new FlowLayoutPanel{Dock=DockStyle.Top,Height=46};SearchStyle(heroSearch);bar.Controls.Add(heroSearch);bar.Controls.Add(Theme.Button("Open selected source",()=>{var h=Selected<HeroRank>(heroes);if(h!=null)Theme.Link(h.url);}));p.Controls.Add(bar);p.Controls.Add(Bar("Search hero names. Lower average placement is better. Selected mode · all ranks · source patch. These are population averages, not lobby-specific odds."));heroSearch.TextChanged+=(s,e)=>FillHeroes();}
 void BuildComps(){var p=Page("Compositions");var split=new SplitContainer{Dock=DockStyle.Fill,SplitterWidth=15};split.Size=new Size(1000,500);split.SplitterDistance=460;Theme.Columns(comps,"Tier","Composition","Avg","Top 4 %");comps.Columns[0].FillWeight=40;comps.Columns[1].FillWeight=190;comps.Columns[2].FillWeight=45;comps.Columns[3].FillWeight=60;split.Panel1.Controls.Add(comps);details.Dock=DockStyle.Fill;details.BackColor=Theme.Panel;details.ForeColor=Theme.Ink;details.Font=Theme.Font(11);split.Panel2.Controls.Add(details);corePreview=new CorePreview(Catalog);split.Panel2.Controls.Add(corePreview);var actions=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=47,Padding=new Padding(0,6,0,0)};actions.Controls.Add(Theme.Button("Pin to overlay",()=>{Overlay.Pinned=selectedComp;Overlay.Invalidate();}));actions.Controls.Add(Theme.Button("Full source guide",()=>{var c=Selected<Comp>(comps);if(c!=null)Theme.Link(c.url);}));split.Panel2.Controls.Add(actions);p.Controls.Add(split);var bar=new FlowLayoutPanel{Dock=DockStyle.Top,Height=43};SearchStyle(compSearch);bar.Controls.Add(compSearch);bar.Controls.Add(Theme.Button("Clear pin",()=>Overlay.Pinned=""));p.Controls.Add(bar);p.Controls.Add(Bar("Source tiers and core setups · select a comp to inspect its pieces. Core overlap is a watchlist, not a recommendation to force a build."));compSearch.TextChanged+=(s,e)=>FillComps();comps.SelectionChanged+=(s,e)=>ShowComp();}
 void BuildCards(){var p=Page("Card library");Theme.Columns(cards,"Tier","Card","Tribe","Attack","Health","Text");cards.Columns[1].FillWeight=170;cards.Columns[5].FillWeight=330;p.Controls.Add(cards);var bar=new FlowLayoutPanel{Dock=DockStyle.Top,Height=45};SearchStyle(cardSearch);bar.Controls.Add(cardSearch);kind.DropDownStyle=ComboBoxStyle.DropDownList;kind.Items.AddRange(new object[]{"Pool minions","Pool spells","Heroes","All BG cards"});kind.SelectedIndex=0;kind.Width=150;bar.Controls.Add(kind);tribe.DropDownStyle=ComboBoxStyle.DropDownList;tribe.Items.AddRange(new object[]{"All tribes","BEAST","DEMON","DRAGON","ELEMENTAL","MECHANICAL","MURLOC","NAGA","PIRATE","QUILBOAR","UNDEAD"});tribe.SelectedIndex=0;tribe.Width=155;bar.Controls.Add(tribe);p.Controls.Add(bar);p.Controls.Add(Bar("HearthstoneJSON · pool flags reflect the client database and may lag server hotfixes. Search names or card text; tavern tier appears in the first column."));cardSearch.TextChanged+=(s,e)=>FillCards();kind.SelectedIndexChanged+=(s,e)=>FillCards();tribe.SelectedIndexChanged+=(s,e)=>FillCards();}
 void BuildStats(){var p=Page("My stats");Theme.Columns(historyGrid,"Finished","Hero","Place","Turns","Client build");p.Controls.Add(historyGrid);statsTitle.Dock=DockStyle.Top;statsTitle.Height=65;statsTitle.Font=Theme.Font(15,true);statsTitle.ForeColor=Theme.Green;p.Controls.Add(statsTitle);var bar=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=43};bar.Controls.Add(Theme.Button("Import a Power log",()=>Import()));bar.Controls.Add(Theme.Button("Export CSV",()=>Export()));p.Controls.Add(bar);p.Controls.Add(Bar("Local results for the selected mode · duplicate matches are ignored. MMR and results missing from the log are not guessed."));}
 void BuildSources(){var p=Page("Setup and sources");sources.Dock=DockStyle.Fill;sources.BackColor=Theme.Bg;sources.ForeColor=Theme.Ink;sources.Font=Theme.Font(11);p.Controls.Add(sources);var bar=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=82,WrapContents=true};bar.Controls.Add(Theme.Button("Choose Hearthstone folder",()=>{using(var d=new FolderBrowserDialog{Description="Choose the folder containing Hearthstone.exe"})if(d.ShowDialog()==DialogResult.OK){if(!File.Exists(Path.Combine(d.SelectedPath,"Hearthstone.exe"))){MessageBox.Show("That folder does not contain Hearthstone.exe.");return;}Settings.HearthstonePath=d.SelectedPath;SaveSettings();lastDiscover=DateTime.MinValue;}}));bar.Controls.Add(Theme.Button("Open Blizzard news",()=>Theme.Link("https://hearthstone.blizzard.com/en-us/news")));bar.Controls.Add(Theme.Button("Source methodology",()=>Theme.Link("https://bgbuddy.gg/about")));bar.Controls.Add(Theme.Button("Overlay smaller",()=>{Settings.OverlayWidth=Math.Max(270,Settings.OverlayWidth-25);SaveSettings();}));bar.Controls.Add(Theme.Button("Overlay larger",()=>{Settings.OverlayWidth=Math.Min(520,Settings.OverlayWidth+25);SaveSettings();}));p.Controls.Add(bar);}
 static T Selected<T>(DataGridView g) where T:class{return g.SelectedRows.Count>0?g.SelectedRows[0].Tag as T:null;}
 public void ShowDashboard(){Show();WindowState=FormWindowState.Normal;Activate();}
 async void OnCombat(FightSnapshot f){ArtCache.Request(f.Enemy.Concat(f.Friendly).Select(x=>x.CardId),Catalog.Cards.build);if((reader!=null&&reader.CaughtUp)&&!Combat.Busy)await Combat.Run(f);}
 public void SavePreferences(){SaveSettings();}public void SaveSession(){try{Store.Write(Catalog.Duos?"session-duos.json":"session.json",Session);}catch(Exception e){error="Session save failed: "+e.Message;}}
 public void SwitchMode(bool duos){if(Catalog.Duos==duos)return;SaveSession();Catalog.Duos=duos;Settings.DataMode=duos?"Duos":"Solo";Session=Store.Read(duos?"session-duos.json":"session.json",new SessionData());if(Rating!=null)Rating.ResetConfirmation();if(Overlay!=null){Overlay.Guide.RefreshRows(true);Overlay.Tools.FilterCards();}Populate();SaveSettings();}
 void SaveSettings(){try{Store.Write("settings.json",Settings);}catch(Exception e){error="Could not save settings: "+e.Message;}UpdateSources();}
 void Populate(){FillHeroes();FillComps();FillCards();FillHistory();UpdateSources();}
 void FillHeroes(){heroes.Rows.Clear();foreach(var h in Catalog.Meta.heroes.Where(x=>x.name.IndexOf(heroSearch.Text,StringComparison.OrdinalIgnoreCase)>=0).OrderBy(x=>x.rank)){int i=heroes.Rows.Add(h.rank,h.name,h.avg.ToString("0.00"),h.pick.ToString("0.0"),h.games);heroes.Rows[i].Tag=h;}}
 void FillComps(){comps.Rows.Clear();foreach(var c in Catalog.BuildMeta.comps.Where(x=>x.name.IndexOf(compSearch.Text,StringComparison.OrdinalIgnoreCase)>=0).OrderBy(x=>"SABCDF".IndexOf(x.tier)).ThenBy(x=>x.avg)){int i=comps.Rows.Add(c.tier,c.name,c.unranked?"—":c.avg.ToString("0.0"),c.unranked?"—":c.top4.ToString("0.0"));comps.Rows[i].Tag=c;}ShowComp();}
 void FillCards(){cards.Rows.Clear();foreach(var c in Catalog.Cards.cards.Where(c=>Catalog.Available(c)&&(kind.SelectedIndex==0?c.pool:kind.SelectedIndex==1?c.spell:kind.SelectedIndex==2?c.hero:true)&&(tribe.SelectedIndex<=0||c.tribe.Contains(tribe.Text))&&(c.name+" "+c.text).IndexOf(cardSearch.Text,StringComparison.OrdinalIgnoreCase)>=0).OrderBy(x=>x.tier).ThenBy(x=>x.name)){cards.Rows.Add(c.tier==0?"—":c.tier.ToString(),c.name,c.tribe,c.attack,c.health,c.text);}}
 void ShowComp(){var c=Selected<Comp>(comps);if(c==null)return;selectedComp=c.name;if(corePreview!=null){corePreview.Comp=c;corePreview.Invalidate();}var lines=new List<string>{c.name.ToUpperInvariant(),"", "Tier "+c.tier+"  ·  "+c.avg.ToString("0.0")+" avg placement",c.first+"% first  ·  "+c.top4+"% top four  ·  "+c.games+" games","",Catalog.Freshness,"", "CORE PIECES (not a positioning order)",""};foreach(var id in c.core){var card=Catalog.Get(id);lines.Add("• "+Catalog.Name(id)+(card==null?" [missing card data]":"  ·  Tavern "+card.tier+(card.pool?"":" [not flagged in pool]")));if(card!=null)lines.Add("   "+card.text);lines.Add("");}lines.Add("OPTIONAL PIECES");foreach(var id in c.addons)lines.Add("• "+Catalog.Name(id));lines.AddRange(new[]{"","SETUP CHECKLIST","Identify the core engine before committing. Keep room to buy and cycle cards. Use each card's current text to decide trigger order, and inspect the opponent before changing positioning.","","The source guide has the build-specific play pattern. Population placement does not predict your current board's combat result.","","Source: "+c.url,"Scope: "+Catalog.BuildMeta.scope});if(!String.IsNullOrEmpty(c.detailError))lines.Add("Board unavailable: "+c.detailError);if(c.unranked){lines.RemoveRange(2,3);lines.InsertRange(2,new[]{"DUOS MECHANIC GUIDE · UNRANKED",c.notes??"","No verified Duos build-placement statistics are available."});}details.Text=String.Join(Environment.NewLine,lines);}
 void FillHistory(){historyGrid.Rows.Clear();var results=history.Where(r=>(r.mode??"").Contains("DUO")==Catalog.Duos).ToList();foreach(var r in results.OrderByDescending(x=>x.endedAt)){DateTime dt;string date=DateTime.TryParse(r.endedAt,out dt)?dt.ToLocalTime().ToString("dd MMM HH:mm"):r.endedAt;historyGrid.Rows.Add(date,Catalog.Name(r.hero),r.placement,r.turns,r.build);}statsTitle.Text=results.Count==0?"No recorded matches yet":results.Count+" matches    ·    "+results.Average(x=>x.placement).ToString("0.00")+" avg place    ·    "+(100.0*results.Count(x=>x.placement<=(Catalog.Duos?2:4))/results.Count).ToString("0")+(Catalog.Duos?"% top two    ·    ":"% top four    ·    ")+results.Count(x=>x.placement==1)+" wins";}
 void Record(MatchRecord r){if(history.Any(x=>x.key==r.key))return;history.Add(r);if(reader!=null&&!importing){bool duo=(r.mode??"").Contains("DUO");if(duo==Catalog.Duos){Session.Add(r);SaveSession();}else{var otherSession=Store.Read(duo?"session-duos.json":"session.json",new SessionData());otherSession.Add(r);Store.Write(duo?"session-duos.json":"session.json",otherSession);}}try{Store.Write("history.json",history);}catch(Exception e){error="History save failed: "+e.Message;}FillHistory();}
 void UpdateSources(){sources.Text=String.Join("\n",new[]{
 "TAVERNLENS — GET CONNECTED","",
 "Exit the previous TavernLens from its tray menu, then run TavernLens.exe. Use Solo or Duos Battlegrounds in windowed or borderless mode.","",
 "Minions opens the illustrated tribe/tavern-tier browser. Builds opens illustrated core and optional cards. Fights opens the latest recorded board for each opponent. Hover a native leaderboard portrait for a row of remembered minion pictures.","",
 "Ctrl+Shift+O shows/hides everything. Ctrl+Shift+Space locks/unlocks interaction. Ctrl+Shift+D opens the dashboard. Closing the dashboard keeps the tray app running.","",
 "Hearthstone folder: "+Settings.HearthstonePath,"Log: "+(String.IsNullOrEmpty(logPath)?"Waiting for Power.log":logPath),"",
 "COMBAT ODDS","",
 "Firestone simulator 1.1.750 runs locally, up to 1,500 simulations per combat. The panel shows win, draw and loss estimates once minion attacks begin. Previous-fight results are labeled during recruitment.","",
 "EXPERIMENTAL: odds are conditional on visible log state. Unknown opponent hand, some global counters, Dark Gift state and unhandled effects can materially change the result. Sampling error is not the only source of error. Unknown cards, unsupported secret/quest/anomaly state, timeouts and new untested card builds withhold results.","",
 "OPPONENT HISTORY","",
 "Snapshots preserve minion order, card identity, attack, health and keywords at combat opening or before the first attack. Start-of-combat effects may already have happened. Boards are per opponent and reset for a new match. Hero-position mapping must be known from the log; an unmapped portrait does not show a guessed board.","",
 "DATA SOURCES","",Catalog.Freshness,"Card build: "+Catalog.Cards.build+" · checked "+Catalog.Cards.updatedAt,"Rankings: "+Catalog.Meta.source,Catalog.Meta.scope,"Retrieved: "+Catalog.Meta.updatedAt,"Official announcement: "+Catalog.Patch.title,Catalog.Patch.url,"",
 "Cards, rankings and patch news refresh on launch and hourly. Images are cached from HearthstoneJSON. Failed sources retain their last usable cache. Simulator program updates require compatibility testing; it will not silently claim support for a new card build.",String.Join("\n",Catalog.Status.errors),"",
 "LOGGING & LIMITS","",
 "If Power.log is missing, run Enable-Logging.ps1 and restart Hearthstone. It backs up log.config and preserves other sections. No memory injection or game input automation is used. Duos, MMR and automated lobby-tribe filtering are not supported.","",
 "Combat snapshots remain local. No account names or log uploads are sent. Artwork requests contain card IDs in the image URLs. Public stats are all-ranks population data, and core-piece lists are not positioning instructions.","",
 "Independent personal tool. Hearthstone art and card text belong to Blizzard. Statistics are attributed to Battlegrounds Buddy / Firestone community data. Simulator dependency notices are included in the simulator folder."
 });}
 async void RefreshWeb(){if(updating)return;updating=true;lastUpdate=DateTime.UtcNow;connection.Text="Refreshing public data…";try{int result=await Task.Run(()=>{var p=Process.Start(new ProcessStartInfo(Path.Combine(Store.Root,"runtime","node.exe"),"\""+Path.Combine(Store.Root,"src","update-data.cjs")+"\""){UseShellExecute=false,CreateNoWindow=true,WorkingDirectory=Store.Root});if(!p.WaitForExit(180000)){p.Kill();throw new Exception("Refresh timed out; cached data retained.");}int code=p.ExitCode;p.Dispose();return code;});var refreshed=await Task.Run(()=>new Catalog());Catalog.Adopt(refreshed);Populate();error=result==0?"":"Some sources could not refresh. See Setup and sources.";}catch(Exception e){error=e.Message;}finally{updating=false;}}
 void Tick(){
  if(closing)return;
  if(lastUpdate==DateTime.MinValue||(DateTime.UtcNow-lastUpdate).TotalHours>=1)RefreshWeb();
  IntPtr target=IntPtr.Zero;bool gameRunning=false;foreach(var p in Process.GetProcessesByName("Hearthstone")){using(p){gameRunning=true;if(p.MainWindowHandle!=IntPtr.Zero){target=p.MainWindowHandle;break;}}}
  try{
   if(target!=IntPtr.Zero&&(DateTime.UtcNow-lastDiscover).TotalSeconds>=3){lastDiscover=DateTime.UtcNow;string root=Path.Combine(Settings.HearthstonePath,"Logs");if(Directory.Exists(root)){var newest=Directory.GetDirectories(root).OrderByDescending(x=>Directory.GetLastWriteTimeUtc(x)).FirstOrDefault();string candidate=newest==null?Path.Combine(root,"Power.log"):Path.Combine(newest,"Power.log");if(File.Exists(candidate)&&(candidate!=logPath||File.GetCreationTimeUtc(candidate)!=logCreated)){if(reader!=null)reader.Dispose();reader=new LiveReader(candidate);logPath=candidate;logCreated=File.GetCreationTimeUtc(candidate);string scenePath=Path.Combine(Path.GetDirectoryName(candidate),"LoadingScreen.log");sceneTail.Dispose();Scenes=new SceneState();if(File.Exists(scenePath))sceneTail.Open(scenePath);State=new MatchState{Stream=candidate};State.OnComplete=Record;State.OnCombat=OnCombat;UpdateSources();}}}
   if(target!=IntPtr.Zero&&!String.IsNullOrEmpty(logPath)){if(reader!=null){State=reader.Latest;if(State.Battlegrounds&&State.Started&&!State.Complete&&!Scenes.InLobby)SwitchMode(State.Duos);if(State.Complete){State.Fights.Clear();State.LastFights.Clear();State.TeamBoards.Clear();State.CurrentFight=null;}foreach(var result in reader.Drain())Record(result);if(reader.Error!="")error="Log reader: "+reader.Error;}sceneTail.Poll(Scenes.Feed);}
  }catch(Exception e){error="Log reader: "+e.Message;}
  var foreground=Native.GetForegroundWindow();Rating.Tick(gameRunning?new IntPtr(1):IntPtr.Zero,Scenes.InLobby&&foreground==target);if(target!=IntPtr.Zero)preview=false;if(preview){Overlay.Follow(Handle,Visible);}else Overlay.Follow(target,!Rating.Selecting&&!Scenes.Loading&&(Scenes.InLobby||(State.Battlegrounds&&(reader!=null&&reader.CaughtUp)&&(Scenes.Scene==""||Scenes.Scene=="GAMEPLAY")))&&(foreground==target||Native.IsOurWindow(foreground)));
  if(!updating)connection.Text=target==IntPtr.Zero?"WAITING FOR HEARTHSTONE":String.IsNullOrEmpty(logPath)?"GAME FOUND · waiting for Power.log":(reader!=null&&!reader.CaughtUp)?"RECOVERING CURRENT MATCH…":!State.Battlegrounds?"CONNECTED · ready for your next match":"CONNECTED · "+(Catalog.Duos?"Duos · ":"Solo · ")+State.Phase;
  fresh.Text=Catalog.Freshness+(String.IsNullOrEmpty(error)?"":"\n"+error);
  if(State.CurrentFight!=null&&(State.CurrentFight.Stage=="After start-of-combat"||(State.Duos&&State.CurrentFight.FriendlyPartner!=null))&&(reader!=null&&reader.CaughtUp)&&Combat.Result.key!=State.CurrentFight.Key&&!Combat.Busy)OnCombat(State.CurrentFight);if(++renders%2==0&&Visible)RenderLive();
 }
 void RenderLive(){var s=State;var h=s.Hero;liveTitle.Text=!s.Battlegrounds?"Ready when you enter Battlegrounds":"Turn "+s.Turn+" · "+s.Phase+" · "+Catalog.Name(h==null?null:h.CardId)+"\n"+(h==null?"":Math.Max(0,h.N("HEALTH")-h.N("DAMAGE"))+" health + "+h.N("ARMOR")+" armor");string signature=s.Key+"|"+s.Phase+"|"+String.Join(";",s.Board(s.Controller).Concat(s.Lobby).Select(x=>x.Id+":"+x.CardId+":"+String.Join(",",x.Tags.OrderBy(t=>t.Key).Select(t=>t.Key+"="+t.Value))));if(signature==liveSignature)return;liveSignature=signature;board.Rows.Clear();if(s.Battlegrounds)foreach(var x in s.Board(s.Controller)){string keys=String.Join(", ",new[]{"TAUNT","DIVINE_SHIELD","REBORN","WINDFURY","VENOMOUS"}.Where(k=>x.N(k)>0).Select(k=>k.Replace('_',' ')));board.Rows.Add(x.N("ZONE_POSITION"),Catalog.Name(x.CardId),x.N("ATK"),Math.Max(0,x.N("HEALTH")-x.N("DAMAGE")),keys);}lobby.Rows.Clear();if(s.Battlegrounds)foreach(var x in s.Lobby)lobby.Rows.Add(Catalog.Name(x.CardId),x.N("PLAYER_TECH_LEVEL"),Math.Max(0,x.N("HEALTH")-x.N("DAMAGE")),x.N("PLAYER_LEADERBOARD_PLACE"));}
 async void Import(){if(importing)return;using(var d=new OpenFileDialog{Filter="Hearthstone Power logs|Power*.log|Log files|*.log",InitialDirectory=Path.Combine(Settings.HearthstonePath,"Logs")}){if(d.ShowDialog()!=DialogResult.OK)return;importing=true;connection.Text="Importing match log…";try{var results=await Task.Run(()=>{var list=new List<MatchRecord>();var state=new MatchState{Stream=d.FileName};state.OnComplete=list.Add;foreach(var line in File.ReadLines(d.FileName))state.Feed(line);return list;});int before=history.Count;foreach(var r in results)Record(r);MessageBox.Show((history.Count-before)+" results imported. Incomplete or unrecognized results are skipped.","TavernLens");}catch(Exception e){MessageBox.Show(e.Message,"Import failed");}finally{importing=false;}}}
 void Export(){using(var d=new SaveFileDialog{Filter="CSV|*.csv",FileName="TavernLens-history.csv"}){if(d.ShowDialog()!=DialogResult.OK)return;try{File.WriteAllLines(d.FileName,new[]{"finished,hero,placement,turns,build,mode"}.Concat(history.Select(x=>Csv(x.endedAt)+","+Csv(Catalog.Name(x.hero))+","+x.placement+","+x.turns+","+Csv(x.build)+","+Csv(x.mode))));}catch(Exception e){MessageBox.Show(e.Message,"Export failed");}}}
 static string Csv(string value){value=value??"";if(value.Length>0&&"=+-@".Contains(value[0]))value="'"+value;return "\""+value.Replace("\"","\"\"")+"\"";}
 protected override void WndProc(ref Message m){if(m.Msg==0x312){int id=m.WParam.ToInt32();if(id==1){Settings.OverlayEnabled=!Settings.OverlayEnabled;SaveSettings();}else if(id==2)Overlay.SetInteractive(!Overlay.Interactive);else if(id==3)ShowDashboard();}base.WndProc(ref m);}
 protected override void Dispose(bool disposing){if(disposing){timer.Stop();timer.Dispose();tail.Dispose();if(reader!=null)reader.Dispose();if(tray!=null)tray.Dispose();if(Overlay!=null)Overlay.Dispose();}base.Dispose(disposing);}
 public void CaptureSidebar(string output){Session=new SessionData();lastUpdate=DateTime.UtcNow;preview=true;Show();Application.DoEvents();Overlay.SetInteractive(true);Overlay.Follow(Handle,true);Directory.CreateDirectory(output);BoardTests.Render(output);SaveShot(this,Path.Combine(output,"App.png"));Overlay.Guide.SelectMode(0);Application.DoEvents();SaveShot(Overlay,Path.Combine(output,"Right-Minions.png"));Overlay.Guide.Preview.Display("BG31_803",null,Overlay.Guide,0);Application.DoEvents();SaveShot(Overlay.Guide.Preview,Path.Combine(output,"Card-Hover.png"));try{using(var screen=new Bitmap(Overlay.Guide.Preview.Width,Overlay.Guide.Preview.Height)){using(var g=Graphics.FromImage(screen))g.CopyFromScreen(Overlay.Guide.Preview.Location,Point.Empty,screen.Size);screen.Save(Path.Combine(output,"Native-Hover.png"));}}catch(System.ComponentModel.Win32Exception){File.WriteAllText(Path.Combine(output,"Native-capture-note.txt"),"Desktop capture is unavailable in this execution session; compositor alpha attributes are verified by native tests.");}Overlay.Guide.Preview.Hide();Overlay.Guide.SelectMode(1);Application.DoEvents();SaveShot(Overlay,Path.Combine(output,"Right-Builds.png"));SaveShot(Overlay.SessionBox,Path.Combine(output,"Left-Session.png"));if(Catalog.BuildMeta.comps.Count>0){Overlay.Guide.OpenBuild(Catalog.BuildMeta.comps[0].name);Application.DoEvents();SaveShot(Overlay,Path.Combine(output,"Build-Details.png"));}Overlay.Pinned=Catalog.BuildMeta.comps.First().name;Overlay.Guide.Collapsed=true;Overlay.Guide.RefreshRows();Overlay.Guide.Sync();Overlay.Follow(Handle,true);Application.DoEvents();SaveShot(Overlay,Path.Combine(output,"Collapsed.png"));closing=true;Close();}
 static void SaveShot(Control c,string path){var until=DateTime.UtcNow.AddMilliseconds(250);while(DateTime.UtcNow<until){Application.DoEvents();System.Threading.Thread.Sleep(10);}using(var image=new Bitmap(c.Width,c.Height)){c.DrawToBitmap(image,new Rectangle(Point.Empty,image.Size));image.Save(path);}}
 public void CapturePreview(string output){lastUpdate=DateTime.UtcNow;Show();Application.DoEvents();foreach(TabPage page in tabs.TabPages){tabs.SelectedTab=page;Application.DoEvents();using(var shot=new Bitmap(Width,Height)){DrawToBitmap(shot,new Rectangle(0,0,Width,Height));shot.Save(Path.Combine(Path.GetDirectoryName(output),"Page-"+tabs.SelectedIndex+".png"));}}tabs.SelectedIndex=2;ShowComp();Application.DoEvents();using(var b=new Bitmap(Width,Height)){DrawToBitmap(b,new Rectangle(0,0,Width,Height));b.Save(output);}Overlay.Tools.Open(0,new Rectangle(20,20,1100,740));Application.DoEvents();using(var b=new Bitmap(Overlay.Tools.Width,Overlay.Tools.Height)){Overlay.Tools.DrawToBitmap(b,new Rectangle(Point.Empty,b.Size));b.Save(Path.Combine(Path.GetDirectoryName(output),"Minion-browser.png"));}Overlay.Tools.Tabs.SelectedIndex=1;Application.DoEvents();using(var b=new Bitmap(Overlay.Tools.Width,Overlay.Tools.Height)){Overlay.Tools.DrawToBitmap(b,new Rectangle(Point.Empty,b.Size));b.Save(Path.Combine(Path.GetDirectoryName(output),"Build-guide.png"));}Overlay.Tools.Tabs.SelectedIndex=2;Application.DoEvents();using(var shot=new Bitmap(Overlay.Tools.Width,Overlay.Tools.Height)){Overlay.Tools.DrawToBitmap(shot,new Rectangle(Point.Empty,shot.Size));shot.Save(Path.Combine(Path.GetDirectoryName(output),"Fight-history.png"));}Size=MinimumSize;tabs.SelectedIndex=3;Application.DoEvents();using(var shot=new Bitmap(Width,Height)){DrawToBitmap(shot,new Rectangle(Point.Empty,shot.Size));shot.Save(Path.Combine(Path.GetDirectoryName(output),"Compact-layout.png"));}closing=true;Close();}
}
public static class Program {public static bool DiagnosticMode;
 [STAThread] public static void Main(string[] args){DiagnosticMode=args.Length>0;Native.SetProcessDPIAware();Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);try{if(args.Length>0&&args[0]=="--test"){Tests.Run(args.Skip(1).ToArray());return;}using(var main=new Main()){if(args.Length==2&&args[0]=="--duos-screenshots"){main.SwitchMode(true);main.CaptureSidebar(args[1]);return;}if(args.Length==2&&args[0]=="--sidebar-screenshots"){main.CaptureSidebar(args[1]);return;}if(args.Length==2&&args[0]=="--screenshot"){main.CapturePreview(args[1]);return;}Application.Run(main);}}catch(Exception e){File.WriteAllText(Path.Combine(Store.Root,"error.txt"),e.ToString());if(args.Length==0)MessageBox.Show(e.Message,"TavernLens could not start");Environment.ExitCode=1;}}
}
}
