using System;
using System.Drawing;
using System.Linq;
using System.Windows.Forms;
namespace TavernLens {
public static class AutoTests {
 public static int Run(){int count=0;Action<bool,string> check=(b,s)=>{if(!b)throw new Exception("Auto overlay test: "+s);count++;};using(var popup=new Floating()){popup.PassThrough(true);uint key,flags;byte alpha;check(Native.GetLayeredWindowAttributes(popup.Handle,out key,out alpha,out flags),"layered popup has compositor attributes");check(alpha==255&&(flags&2)!=0,"full opacity initialized for popup");popup.PassThrough(false);check((Native.GetWindowLong(popup.Handle,-20)&0x20)==0,"popup interaction toggle");}
 var catalog=new Catalog();foreach(var c in catalog.Cards.cards.Where(c=>c.pool&&c.premium>0)){var gold=catalog.Golden(c.id);check(gold!=null&&gold.dbfId==c.premium&&gold.normal==c.dbfId,"explicit golden identity: "+c.id);check(catalog.Golden(gold.id)==gold,"golden hover resolves same pair");}check(catalog.Golden("BG31_803").attack==2&&catalog.Golden("BG31_803").health==2,"golden base stats from data");
 var blocks=new[]{new OcrBlock{text="Ratine",x=139,y=76,w=139,h=35},new OcrBlock{text="4067",x=154,y=139,w=118,h=41},new OcrBlock{text="200",x=800,y=400,w=80,h=30}};check(RatingReader.Locate(blocks)==4067,"rating found automatically near label");check(!RatingReader.Locate(blocks.Skip(1)).HasValue,"unanchored digits ignored");check(!RatingReader.Locate(blocks.Concat(new[]{new OcrBlock{text="Rating",x=600,y=76,w=139,h=35},new OcrBlock{text="8000",x=600,y=139,w=118,h=41}})).HasValue,"conflicting rating widgets rejected");
 using(var main=new Main()){var card=main.Catalog.Cards.cards.First(c=>c.pool&&c.tribe.Contains("BEAST"));main.Settings.PinnedCards.Add(card.id);check(OverlayContext.Watched(main,card.id),"individual card watch");check(main.Overlay.HasPins,"individual pin reserves collapsed shelf");using(var image=new Bitmap(340,150)){var shelf=main.Overlay.Guide.Controls.OfType<PinnedShelf>().Single();shelf.Size=image.Size;shelf.DrawToBitmap(image,new Rectangle(Point.Empty,image.Size));}check(true,"individual pin renders without a build");main.Settings.PinnedCards.Clear();main.Settings.PinnedTribes.Add("BEAST");check(OverlayContext.Watched(main,card.id),"tribe watch");main.Overlay.Guide.SelectMode(3);check(main.Overlay.Guide.Controls.OfType<RibbonList>().Single().Rows.Any(r=>r.Title=="Waiting for your next match"),"context empty state");}
 var state=new MatchState{Stream=@"C:\fixture\Power.log"};foreach(var line in new[]{"CREATE_GAME","GameEntity EntityID=1","tag=TURN value=3","FULL_ENTITY - Creating ID=20 CardID=hero","tag=CARDTYPE value=HERO","tag=PLAYER_ID value=2","tag=PLAYER_TECH_LEVEL value=2","TAG_CHANGE Entity=1 tag=TURN value=7","TAG_CHANGE Entity=20 tag=PLAYER_TECH_LEVEL value=3"})state.Feed("D 12:00:00 PowerTaskList.DebugPrintPower() - "+line);check(state.TierHistory[2].Count==2&&state.TierHistory[2][1].Turn==4,"observed opponent tier timeline");foreach(var line in new[]{"Player EntityID=2 PlayerID=1","tag=CONTROLLER value=1"})state.Feed("D 12:00:00 PowerTaskList.DebugPrintPower() - "+line);state.Feed("GameState.DebugPrintEntityChoices() - ChoiceType=MULLIGAN");state.Feed("GameState.DebugPrintEntityChoices() - Entities[0]=[cardId=BG20_HERO_280 player=1]");state.Feed("GameState.DebugPrintEntityChoices() - Entities[1]=[cardId=other player=2]");check(state.Choices.Count==1&&state.Choices[0]=="BG20_HERO_280","offered heroes limited to own controller");check(HeroChoices.BaseHero("TB_BaconShop_HERO_70_SKIN_I")=="TB_BaconShop_HERO_70","cosmetic hero resolves to stats identity");state.Feed("D 12:00:01 PowerTaskList.DebugPrintPower() - CREATE_GAME");check(state.TierHistory.Count==0,"timeline clears for new match");return count;
 }
}
}

