using System;
using System.IO;
using System.Drawing;
using System.Linq;
using System.Collections.Generic;
namespace TavernLens {
public static class BoardTests {
 static Entity Hero(int id,int pid,int place,string zone){return new Entity{Id=id,CardId="hero"+pid,Tags=new Dictionary<string,string>{{"CARDTYPE","HERO"},{"PLAYER_ID",pid.ToString()},{"PLAYER_LEADERBOARD_PLACE",place.ToString()},{"ZONE",zone}}};}
 public static int Run(){int count=0;Action<bool,string> check=(ok,msg)=>{if(!ok)throw new Exception("Board/hero test: "+msg);count++;};var s=new MatchState();s.Entities[135]=Hero(135,1,6,"SETASIDE");s.Entities[1371]=Hero(1371,1,0,"REMOVEDFROMGAME");s.Entities[1434]=Hero(1434,1,0,"PLAY");check(s.Portrait(5).Id==135,"permanent hero wins over newer combat clones");s.Entities[135].Tags["PLAYER_LEADERBOARD_PLACE"]="3";check(s.Portrait(2).Id==135&&s.Portrait(5)==null,"portrait follows updated standings");s.Entities[200]=Hero(200,2,3,"SETASIDE");check(s.Portrait(2)==null,"transient duplicate position is not guessed");s.Entities[200].Tags["PLAYER_LEADERBOARD_PLACE"]="4";check(s.Portrait(2).N("PLAYER_ID")==1,"mapping recovers after standings update");
 s.Started=true;s.Entities[2]=new Entity{Id=2,Tags=new Dictionary<string,string>{{"CARDTYPE","PLAYER"},{"PLAYER_ID","1"},{"CONTROLLER","1"}}};s.Feed("GameState.DebugPrintEntityChoices() - ChoiceType=MULLIGAN");s.Feed("GameState.DebugPrintEntityChoices() - Entities[0]=[id=80 zone=HAND zonePos=3 cardId=third player=1]");s.Feed("GameState.DebugPrintEntityChoices() - Entities[1]=[id=81 zone=HAND zonePos=1 cardId=first player=1]");check(s.Choices.OrderBy(id=>s.ChoicePositions[id]).First()=="first","hero badges follow card positions rather than arrival order");
 s.Entities[80]=new Entity{Id=80,CardId="third",Tags=new Dictionary<string,string>{{"ZONE","HAND"},{"CONTROLLER","1"},{"ZONE_POSITION","1"}}};s.Entities[81]=new Entity{Id=81,CardId="first",Tags=new Dictionary<string,string>{{"ZONE","HAND"},{"CONTROLLER","1"},{"ZONE_POSITION","3"}}};check(HeroChoices.Position(s,"third")==1&&HeroChoices.Position(s,"first")==3,"updated hand positions override original offer order");using(var main=new Main()){var popup=main.Overlay.Guide.Preview;uint key,flags;byte alpha;check(Native.GetLayeredWindowAttributes(popup.Handle,out key,out alpha,out flags)&&(flags&3)==3&&key==0x030201,"card preview uses actual window colour-key transparency");using(var bitmap=new Bitmap(popup.Width,popup.Height)){popup.DrawToBitmap(bitmap,new Rectangle(Point.Empty,bitmap.Size));check(bitmap.GetPixel(0,0).ToArgb()==popup.TransparencyKey.ToArgb(),"no painted border around card preview");}}
 var match=new MatchState{Mode="GT_BATTLEGROUNDS",Key="fixture",Started=true};match.Entities[1]=new Entity{Id=1,Tags=new Dictionary<string,string>{{"TURN","2"}}};match.Entities[2]=new Entity{Id=2,Tags=new Dictionary<string,string>{{"CARDTYPE","PLAYER"},{"PLAYER_ID","1"},{"CONTROLLER","1"}}};match.Entities[3]=new Entity{Id=3,Tags=new Dictionary<string,string>{{"CARDTYPE","PLAYER"},{"PLAYER_ID","9"},{"CONTROLLER","9"},{"BACON_DUMMY_PLAYER","1"},{"HERO_ENTITY","50"},{"BACON_CURRENT_COMBAT_PLAYER_ID","2"}}};match.Entities[50]=Hero(50,2,3,"PLAY");foreach(int id in new[]{71,72})match.Entities[id]=new Entity{Id=id,CardId="BG31_803",Tags=new Dictionary<string,string>{{"CARDTYPE","MINION"},{"CONTROLLER","9"},{"ZONE","PLAY"},{"ZONE_POSITION",id==71?"2":"1"},{"ATK","4"},{"HEALTH","5"}}};match.CaptureFight();var remembered=match.LastFights[2];check(remembered.Enemy[0].Id==72&&remembered.Enemy[1].Id==71,"remembered minions preserve left-to-right board order");match.Entities[72].Tags["ATK"]="99";match.Entities[72].Tags["ZONE_POSITION"]="7";check(remembered.Enemy[0].N("ATK")==4&&remembered.Enemy[0].N("ZONE_POSITION")==1,"live changes cannot mutate remembered board");match.Entities[1].Tags["TURN"]="4";match.Entities[3].Tags["BACON_CURRENT_COMBAT_PLAYER_ID"]="3";match.Entities[50].Tags["PLAYER_ID"]="3";match.CaptureFight();check(match.LastFights.Count==2&&match.LastFights[2]==remembered&&match.LastFights[3].Enemy[0].Id==71,"next opponent keeps a separate ordered board");
 var ranks=Enumerable.Range(1,100).Select(i=>new HeroRank{id="h"+i,avg=3+i*.02}).ToList();check(HeroChoices.Grade(ranks[0],ranks)=="S"&&HeroChoices.Grade(ranks[99],ranks)=="D","derived tiers span ranking");check(HeroChoices.Grade(null,ranks)=="—","no fabricated missing tier");foreach(int height in new[]{720,1080,1440})foreach(int n in new[]{2,4}){var game=new Rectangle(0,0,height*16/9,height);var boxes=Enumerable.Range(0,n).Select(i=>HeroChoices.BadgeBounds(game,i,n)).ToArray();check(boxes.All(b=>game.Contains(b)),"badges remain inside client");check(boxes.Zip(boxes.Skip(1),(a,b)=>!a.IntersectsWith(b)).All(v=>v),"badges do not overlap");}
 return count;}
 public static void Render(string output){using(var canvas=new Bitmap(960,108))using(var g=Graphics.FromImage(canvas)){g.Clear(Theme.Bg);int i=0;foreach(string tier in new[]{"S","A","B","C"})using(var badge=new HeroBadge()){badge.Set("Hero rating preview",tier,3.85+i*.22);using(var tile=new Bitmap(badge.Width,badge.Height)){badge.DrawToBitmap(tile,new Rectangle(Point.Empty,tile.Size));g.DrawImageUnscaled(tile,18+i*236,20);}i++;}canvas.Save(Path.Combine(output,"Hero-Ratings.png"));}}
}
}
