using System;using System.Drawing;using System.Linq;using System.Windows.Forms;
namespace TavernLens {
public class DuosHistoryPopup:Floating {
 readonly Main main;int place;
 public DuosHistoryPopup(Main m){main=m;PassThrough(true);}
 public static int TeamAt(Point p,Rectangle game){double tile=game.Height*.69*.863/8,space=game.Height*.69*.137/3;double left=game.Left+(game.Width-game.Height*4.0/3)/2;for(int team=0;team<4;team++){double y=game.Top+game.Height*.15+team*(tile*2+space);if(p.Y>=y&&p.Y<y+tile*2&&p.X>=left-8&&p.X<=left+game.Height*.105)return team+1;}return -1;}
 public void Display(int team,Rectangle game){place=team;int width=Math.Min(820,game.Width-100),height=Math.Min(430,game.Height-150);Place(new Rectangle(game.X+(game.Width-width)/2,game.Y+16,width,height));Invalidate();}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);var heroes=main.State.Lobby.Where(h=>h.N("PLAYER_LEADERBOARD_PLACE")==place).OrderBy(h=>h.N("PLAYER_ID")).Take(2).ToList();if(heroes.Count!=2){using(var f=Theme.Font(11))TextRenderer.DrawText(e.Graphics,"Waiting for this team's identities",f,new Point(16,18),Theme.Muted);return;}int rowHeight=Height/2;for(int row=0;row<2;row++){var hero=heroes[row];FightSnapshot fight;main.State.LastFights.TryGetValue(hero.N("PLAYER_ID"),out fight);int y=row*rowHeight;using(var font=Theme.Font(10,true))TextRenderer.DrawText(e.Graphics,main.Catalog.Name(hero.CardId)+(fight==null?" · board not revealed":" · last seen turn "+fight.Turn),font,new Rectangle(14,y+8,Width-28,26),row==0?Theme.Gold:Theme.Green,TextFormatFlags.EndEllipsis);if(fight==null)continue;int w=(Width-28)/7;for(int i=0;i<fight.Enemy.Count;i++){var unit=fight.Enemy[i];var art=ArtCache.Get(unit.CardId,main.Catalog.Cards.build);var rect=new Rectangle(14+i*w,y+36,w-5,rowHeight-62);if(art!=null)e.Graphics.DrawImage(art,CardTile.Fit(art,rect));else{ArtCache.Request(new[]{unit.CardId},main.Catalog.Cards.build);using(var f=Theme.Font(8))TextRenderer.DrawText(e.Graphics,main.Catalog.Name(unit.CardId),f,rect,Theme.Ink,TextFormatFlags.WordBreak);}using(var f=Theme.Font(9,true))TextRenderer.DrawText(e.Graphics,unit.N("ATK")+" / "+Math.Max(0,unit.N("HEALTH")-unit.N("DAMAGE")),f,new Rectangle(rect.X,y+rowHeight-24,rect.Width,22),Theme.Green,TextFormatFlags.HorizontalCenter);}}}
}
}
