using System;using System.Drawing;using System.Linq;using System.Windows.Forms;
namespace TavernLens {
public class DuosHistoryPopup:Floating {
 readonly Main main;int place;int[] rowHeights=new[]{64,64};
 public DuosHistoryPopup(Main m){main=m;PassThrough(true);}
 public static int TeamAt(Point p,Rectangle game){double tile=game.Height*.69*.863/8,space=game.Height*.69*.137/3;double left=game.Left+(game.Width-game.Height*4.0/3)/2;for(int team=0;team<4;team++){double y=game.Top+game.Height*.15+team*(tile*2+space);if(p.Y>=y&&p.Y<y+tile*2&&p.X>=left-8&&p.X<=left+game.Height*.105)return team+1;}return -1;}
 Entity[] Heroes(){return main.State.Lobby.Where(h=>h.N("PLAYER_LEADERBOARD_PLACE")==place).OrderBy(h=>h.N("PLAYER_ID")).Take(2).ToArray();}
 public void Display(int team,Rectangle game){place=team;var heroes=Heroes();int width=300;for(int i=0;i<2;i++){FightSnapshot f=null;if(i<heroes.Length)main.State.LastFights.TryGetValue(heroes[i].N("PLAYER_ID"),out f);var size=HistoryLayout.Measure(f==null?0:f.Enemy.Count,270,game);width=Math.Max(width,size.Width);rowHeights[i]=size.Height;}int height=heroes.Length==2?rowHeights.Sum():64;Place(new Rectangle(game.X+(game.Width-width)/2,game.Y+16,width,height));Invalidate();}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);var heroes=Heroes();if(heroes.Length!=2){using(var f=Theme.Font(10))TextRenderer.DrawText(e.Graphics,"Waiting for this team's identities",f,new Point(12,18),Theme.Muted);return;}int y=0;for(int row=0;row<2;row++){var hero=heroes[row];FightSnapshot fight;main.State.LastFights.TryGetValue(hero.N("PLAYER_ID"),out fight);using(var font=Theme.Font(9.5f,true))TextRenderer.DrawText(e.Graphics,main.Catalog.Name(hero.CardId)+(fight==null?" · board not revealed":" · Turn "+fight.Turn),font,new Rectangle(12,y+8,Width-24,26),row==0?Theme.Gold:Theme.Green,TextFormatFlags.EndEllipsis);if(fight!=null){int w=Math.Min(112,(Width-20)/Math.Max(1,fight.Enemy.Count)),left=(Width-w*fight.Enemy.Count)/2;for(int i=0;i<fight.Enemy.Count;i++){var unit=fight.Enemy[i];var art=PortraitCache.Get(main.Catalog.BaseId(unit.CardId),main.Catalog.Cards.build);var rect=new Rectangle(left+i*w,y+40,w-4,rowHeights[row]-48);if(art!=null)RecordedCard.Draw(e.Graphics,art,rect,unit,RecordedCard.Golden(unit,main.Catalog));else using(var f=Theme.Font(8))TextRenderer.DrawText(e.Graphics,main.Catalog.Name(unit.CardId),f,rect,Theme.Ink,TextFormatFlags.WordBreak);}}y+=rowHeights[row];}}
}
}
