using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.IO;
using System.Linq;
using System.Diagnostics;
using System.Threading.Tasks;
using System.Windows.Forms;
namespace TavernLens {
public static class ArtCache {
 static System.Collections.Concurrent.ConcurrentDictionary<string,Image> cache=new System.Collections.Concurrent.ConcurrentDictionary<string,Image>();
 static System.Collections.Concurrent.ConcurrentDictionary<string,bool> loading=new System.Collections.Concurrent.ConcurrentDictionary<string,bool>();
 static HashSet<string> pending=new HashSet<string>();static Dictionary<string,DateTime> attempted=new Dictionary<string,DateTime>();static bool busy;static int notification;
 public static event Action Changed;
 static void Notify(){if(System.Threading.Interlocked.Exchange(ref notification,1)!=0)return;Task.Run(async()=>{await Task.Delay(80);System.Threading.Interlocked.Exchange(ref notification,0);if(Changed!=null)Changed();});}
 public static Image Get(string id,string build){if(String.IsNullOrEmpty(id))return null;string key=build+"/"+id;Image img;if(cache.TryGetValue(key,out img))return img;if(loading.TryAdd(key,true))Task.Run(()=>{try{string file=Path.Combine(Store.Data,"art","verified-v2",build??"",id+".png");if(File.Exists(file)){using(var source=Image.FromFile(file))cache[key]=new Bitmap(source);Notify();}}catch{}});return null;}
 public static void Request(IEnumerable<string> ids,string build){foreach(var id in ids.Where(x=>!String.IsNullOrEmpty(x)).Distinct()){Get(id,build);string key=build+"/"+id;DateTime previous;if(!File.Exists(Path.Combine(Store.Data,"art","verified-v2",build??"",id+".png"))&&(!attempted.TryGetValue(key,out previous)||(DateTime.UtcNow-previous).TotalMinutes>=1)){pending.Add(id);attempted[key]=DateTime.UtcNow;}}Flush();}
 static async void Flush(){if(busy||pending.Count==0)return;busy=true;var ids=pending.Take(80).ToArray();foreach(var id in ids)pending.Remove(id);try{await Task.Run(()=>{using(var p=new Process{StartInfo=new ProcessStartInfo(Path.Combine(Store.Root,"runtime","node.exe"),"\""+Path.Combine(Store.Root,"src","cache-art.cjs")+"\""){UseShellExecute=false,CreateNoWindow=true,RedirectStandardInput=true,RedirectStandardOutput=true,RedirectStandardError=true}}){p.Start();p.StandardOutput.ReadToEndAsync();p.StandardError.ReadToEndAsync();p.StandardInput.Write(Store.Json().Serialize(ids));p.StandardInput.Close();if(!p.WaitForExit(90000))p.Kill();}});}catch{}finally{busy=false;loading.Clear();Notify();Flush();}}
 public static void Dispose(){foreach(var image in cache.Values)image.Dispose();cache.Clear();}
}
public class Floating : Form {
 public bool CaptureExcluded;protected override void OnHandleCreated(EventArgs e){base.OnHandleCreated(e);CaptureExcluded=false;}
 public Floating(){FormBorderStyle=FormBorderStyle.None;ShowInTaskbar=false;TopMost=true;DoubleBuffered=true;BackColor=Theme.Panel;ForeColor=Theme.Ink;Font=Theme.Font();}
 protected override bool ShowWithoutActivation{get{return true;}}
 protected override CreateParams CreateParams{get{var p=base.CreateParams;p.ExStyle|=0x80;return p;}}
 public void PassThrough(bool value){int s=Native.GetWindowLong(Handle,-20);Native.SetWindowLong(Handle,-20,value?s|0x20|0x80000:s&~0x20);if(value||(s&0x80000)!=0)Native.SetLayeredWindowAttributes(Handle,TransparencyKey.IsEmpty?0u:(uint)(TransparencyKey.R|(TransparencyKey.G<<8)|(TransparencyKey.B<<16)),(byte)Math.Max(1,Math.Round(Opacity*255)),TransparencyKey.IsEmpty?2u:3u);}
 public void Place(Rectangle b){if(Visible&&Bounds==b)return;Native.SetWindowPos(Handle,new IntPtr(-1),b.X,b.Y,b.Width,b.Height,0x10|0x40);if(!Visible)Show();}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);using(var pen=new Pen(Design.Border))e.Graphics.DrawRectangle(pen,0,0,Width-1,Height-1);}
}
public class CardTile : Control {
 bool hovered;public Card Card;public Entity Observed;public string Role="";readonly Catalog catalog;readonly Action<Card,Control> hover;readonly Action leave;
 public CardTile(Catalog c,Card card,Entity observed,Action<Card,Control> onHover,Action onLeave){catalog=c;Card=card;Observed=observed;hover=onHover;leave=onLeave;Size=new Size(144,240);Margin=new Padding(7);DoubleBuffered=true;BackColor=Theme.Bg;MouseEnter+=(s,e)=>{hovered=true;Invalidate();if(hover!=null)hover(Card,this);};MouseLeave+=(s,e)=>{hovered=false;Invalidate();if(leave!=null)leave();};}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);var g=e.Graphics;g.InterpolationMode=InterpolationMode.HighQualityBicubic;Design.Surface(g,new Rectangle(1,1,Width-3,Height-3),hovered?Color.FromArgb(38,38,48):Theme.Panel,hovered?Theme.Gold:Design.Border);var image=ArtCache.Get(Card.id,catalog.Cards.build);if(image!=null){var r=Fit(image,new Rectangle(5,4,Width-10,184));g.DrawImage(image,r);}else{using(var b=new SolidBrush(Theme.Panel))g.FillRectangle(b,3,4,Width-6,156);using(var f=Theme.Font(11,true))TextRenderer.DrawText(g,Card.name,f,new Rectangle(9,40,Width-18,90),Theme.Gold,TextFormatFlags.WordBreak|TextFormatFlags.HorizontalCenter);}
  using(var f=Theme.Font(8.5f,true))TextRenderer.DrawText(g,Card.name,f,new Rectangle(7,185,Width-14,29),Theme.Ink,TextFormatFlags.WordBreak|TextFormatFlags.HorizontalCenter|TextFormatFlags.EndEllipsis);
  string text=Observed==null?(Role==""?"TIER "+Card.tier:Role):Observed.N("ATK")+" ATK  /  "+Math.Max(0,Observed.N("HEALTH")-Observed.N("DAMAGE"))+" HP";
  using(var f=Theme.Font(8,true))TextRenderer.DrawText(g,text,f,new Rectangle(0,217,Width,18),Observed==null?Theme.Muted:Theme.Green,TextFormatFlags.HorizontalCenter);
 }
 public static Rectangle Fit(Image image,Rectangle box){double scale=Math.Min((double)box.Width/image.Width,(double)box.Height/image.Height);int w=(int)(image.Width*scale),h=(int)(image.Height*scale);return new Rectangle(box.X+(box.Width-w)/2,box.Y+(box.Height-h)/2,w,h);}
}
public class CardZoom : Floating {
 Card card;Catalog catalog;
 public CardZoom(){Size=new Size(245,330);BackColor=Color.FromArgb(1,2,3);TransparencyKey=BackColor;PassThrough(true);}
 public void Display(Card c,Control anchor,Catalog data){card=c;catalog=data;var p=anchor.PointToScreen(new Point(anchor.Width+5,0));var screen=Screen.FromControl(anchor).WorkingArea;if(p.X+Width>screen.Right)p.X=anchor.PointToScreen(Point.Empty).X-Width-5;p.Y=Math.Max(screen.Top,Math.Min(p.Y,screen.Bottom-Height));Place(new Rectangle(p,Size));Invalidate();}
 protected override void OnPaint(PaintEventArgs e){e.Graphics.Clear(BackColor);if(card==null)return;var art=ArtCache.Get(card.id,catalog.Cards.build);if(art!=null)e.Graphics.DrawImage(art,CardTile.Fit(art,ClientRectangle));}

}
public class CardGallery : FlowLayoutPanel {
 readonly Catalog catalog;readonly CardZoom zoom;public int CardCount;
 public CardGallery(Catalog c,CardZoom z){catalog=c;zoom=z;Dock=DockStyle.Fill;AutoScroll=true;BackColor=Theme.Bg;Padding=new Padding(16);}
 public void ShowCards(IEnumerable<string> ids,IEnumerable<Entity> observed=null,string role=""){
  SuspendLayout();foreach(Control c in Controls.Cast<Control>().ToArray())c.Dispose();Controls.Clear();var list=ids.ToList();CardCount=list.Count;var entities=observed==null?new List<Entity>():observed.ToList();int index=0;foreach(string id in list){var card=catalog.Get(id)??new Card{id=id,name=id,tribe=""};var entity=index<entities.Count?entities[index]:null;var tile=new CardTile(catalog,card,entity,(c,a)=>zoom.Display(c,a,catalog),()=>zoom.Hide()){Role=role};Controls.Add(tile);index++;}if(list.Count==0)Controls.Add(Theme.Label("No cards to show for this selection yet.",0,0,380,40,11,Theme.Muted));ResumeLayout();ArtCache.Request(list,catalog.Cards.build);
 }
}
public class Workbench : Floating {
 readonly Main main;public readonly TabControl Tabs=new TabControl();public CardGallery Browser,Guide,History;public readonly TextBox Search=new TextBox();public ComboBox Tribe=new DarkCombo(),Tier=new DarkCombo(),Builds=new DarkCombo(),Opponents=new DarkCombo();readonly Label guideInfo=new Label(),historyInfo=new Label();readonly CardZoom zoom;string historySignature="";
 public Workbench(Main m,CardZoom z){main=m;zoom=z;Text="TavernLens illustrated overlays";Size=new Size(1020,650);
  var top=new Panel{Dock=DockStyle.Top,Height=77,BackColor=Theme.Panel};top.Controls.Add(Theme.Label("The field guide",24,12,430,32,22,Theme.Ink));top.Controls.Add(Theme.Label("TAVERNLENS  /  YOUR IN-GAME REFERENCE",26,48,470,20,8,Theme.Gold));var close=Theme.Button("Close  ×",()=>{Hide();zoom.Hide();});close.Anchor=AnchorStyles.Top|AnchorStyles.Right;close.SetBounds(890,20,94,35);top.Size=new Size(1020,77);top.Controls.Add(close);Controls.Add(top);Tabs.Dock=DockStyle.Fill;Design.Tabs(Tabs);var deck=Design.MountDeck(Tabs);Controls.Add(deck);deck.BringToFront();var nav=new FlowLayoutPanel{Dock=DockStyle.Top,Height=54,Padding=new Padding(18,7,0,0),BackColor=Theme.Panel};deck.Parent.Controls.Add(nav);nav.BringToFront();string[] names={"Minion browser","Build guides","Fight history"};for(int i=0;i<names.Length;i++){int index=i;var button=new SoftButton{Text=names[i],Size=new Size(164,38),Margin=new Padding(0,0,9,0),Active=i==0};button.Click+=(s,e)=>Tabs.SelectedIndex=index;nav.Controls.Add(button);}Controls.SetChildIndex(deck,0);Controls.SetChildIndex(nav,1);Controls.SetChildIndex(top,2);Tabs.SelectedIndexChanged+=(s,e)=>{for(int i=0;i<nav.Controls.Count;i++){var button=(SoftButton)nav.Controls[i];button.Active=i==Tabs.SelectedIndex;button.Invalidate();}};

  var b=Page("Minion browser");var filters=Bar();SetupCombo(Tribe,175);Tribe.Items.AddRange(new object[]{"BEAST","DEMON","DRAGON","ELEMENTAL","MECHANICAL","MURLOC","NAGA","PIRATE","QUILBOAR","UNDEAD","ALL"});Tribe.SelectedIndex=0;SetupCombo(Tier,130);Tier.Items.AddRange(new object[]{"All tiers","Tier 1","Tier 2","Tier 3","Tier 4","Tier 5","Tier 6","Tier 7"});Tier.SelectedIndex=1;filters.Controls.Add(Tribe);filters.Controls.Add(Tier);Search.Width=260;Search.BackColor=Theme.Bg;Search.ForeColor=Theme.Ink;Search.BorderStyle=BorderStyle.FixedSingle;Search.Font=Theme.Font(11);Search.Margin=new Padding(6,5,8,0);Search.AccessibleName="Search minion name or card text";filters.Controls.Add(Search);filters.Controls.Add(Theme.Label("Search name or card text",0,0,220,30,9,Theme.Muted));Search.TextChanged+=(s,e)=>FilterCards();Browser=new CardGallery(main.Catalog,zoom);b.Controls.Add(Browser);b.Controls.Add(filters);Tribe.SelectedIndexChanged+=(s,e)=>FilterCards();Tier.SelectedIndexChanged+=(s,e)=>FilterCards();
  var g=Page("Build guides");var choose=Bar();SetupCombo(Builds,310);foreach(var c in main.Catalog.BuildMeta.comps)Builds.Items.Add(c.name);choose.Controls.Add(Builds);choose.Controls.Add(Theme.Button("Pin this build",()=>{main.Overlay.Pinned=Builds.Text;main.Overlay.Invalidate();}));choose.Controls.Add(Theme.Button("Full guide",()=>{var c=main.Catalog.BuildMeta.comps.FirstOrDefault(x=>x.name==Builds.Text);if(c!=null)Theme.Link(c.url);}));Guide=new CardGallery(main.Catalog,zoom);g.Controls.Add(Guide);guideInfo.Dock=DockStyle.Top;guideInfo.Height=75;guideInfo.ForeColor=Theme.Muted;guideInfo.Padding=new Padding(24,10,24,0);g.Controls.Add(guideInfo);g.Controls.Add(choose);Builds.SelectedIndexChanged+=(s,e)=>ShowGuide();if(Builds.Items.Count>0)Builds.SelectedIndex=0;
  var h=Page("Fight history");var select=Bar();SetupCombo(Opponents,370);select.Controls.Add(Opponents);select.Controls.Add(Theme.Button("Refresh",()=>RefreshHistory(true)));History=new CardGallery(main.Catalog,zoom);h.Controls.Add(History);historyInfo.Dock=DockStyle.Top;historyInfo.Height=54;historyInfo.Padding=new Padding(10,5,0,0);historyInfo.ForeColor=Theme.Muted;h.Controls.Add(historyInfo);h.Controls.Add(select);Opponents.SelectedIndexChanged+=(s,e)=>ShowHistory();FilterCards();RefreshHistory(true);Design.StyleTree(this);
 }
 TabPage Page(string name){var p=new TabPage(name){BackColor=Theme.Bg,ForeColor=Theme.Ink};Tabs.TabPages.Add(p);return p;}
 static FlowLayoutPanel Bar(){return new FlowLayoutPanel{Dock=DockStyle.Top,Height=57,Padding=new Padding(20,10,0,0),BackColor=Theme.Panel};}
 static void SetupCombo(ComboBox c,int width){c.DropDownStyle=ComboBoxStyle.DropDownList;c.Width=width;c.Font=Theme.Font(11);c.Margin=new Padding(0,3,10,0);}
 public void FilterCards(){string tribe=Tribe.Text;Browser.ShowCards(main.Catalog.Cards.cards.Where(c=>main.Catalog.Available(c)&&c.pool&&(c.name+" "+c.text).IndexOf(Search.Text,StringComparison.OrdinalIgnoreCase)>=0&&(Tier.SelectedIndex==0||c.tier==Tier.SelectedIndex)&&(tribe=="ALL"||c.tribe.Split('/').Any(t=>t.Trim()==tribe)||c.tribe=="ALL")).OrderBy(c=>c.tier).ThenBy(c=>c.name).Select(c=>c.id));}
 public void ReloadMode(){Builds.Items.Clear();foreach(var c in main.Catalog.BuildMeta.comps)Builds.Items.Add(c.name);if(Builds.Items.Count>0)Builds.SelectedIndex=0;else Guide.ShowCards(new string[0]);FilterCards();}
 public void ShowGuide(){var c=main.Catalog.BuildMeta.comps.FirstOrDefault(x=>x.name==Builds.Text);if(c==null)return;guideInfo.Text=c.unranked?"DUOS MECHANIC GUIDE · UNRANKED\n"+c.notes:"Solo statistics · Tier "+c.tier+" · "+c.avg.ToString("0.0")+" avg place · "+c.top4+"% top four · "+c.games+" games\nCore pieces first, followed by optional pieces. This is not a positioning order. "+main.Catalog.Freshness;Guide.ShowCards(c.core.Concat(c.addons));for(int i=0;i<Guide.Controls.Count;i++){var tile=Guide.Controls[i] as CardTile;if(tile!=null)tile.Role=i<c.core.Count?"CORE · TIER "+tile.Card.tier:"OPTIONAL · TIER "+tile.Card.tier;}}
 public void RefreshHistory(bool force=false){string signature=main.State.Key+"|"+String.Join(";",main.State.LastFights.Values.Select(f=>f.Key));if(!force&&signature==historySignature)return;historySignature=signature;Opponents.Items.Clear();foreach(var f in main.State.LastFights.Values.OrderByDescending(x=>x.Turn))Opponents.Items.Add(new FightChoice{Fight=f,Text=main.Catalog.Name(f.HeroId)+" · turn "+f.Turn});if(Opponents.Items.Count>0)Opponents.SelectedIndex=0;else{historyInfo.Text="Boards are remembered after you face an opponent. Nothing is inferred for unseen opponents.";History.ShowCards(new string[0]);}}
 void ShowHistory(){var item=Opponents.SelectedItem as FightChoice;if(item==null)return;var f=item.Fight;historyInfo.Text="Last seen: turn "+f.Turn+" · "+Math.Max(0,main.State.Turn-f.Turn)+" turns ago · "+f.Stage+"\nAttack and health below each image are the recorded values.";History.ShowCards(f.Enemy.Select(x=>x.CardId),f.Enemy);}
 public void Open(int tab,Rectangle game){Tabs.SelectedIndex=tab;RefreshHistory();int width=Math.Min(1020,game.Width-60),height=Math.Min(650,game.Height-80);Place(new Rectangle(game.X+(game.Width-width)/2,game.Y+Math.Max(40,(game.Height-height)/2),width,height));}
 class FightChoice{public FightSnapshot Fight;public string Text;public override string ToString(){return Text;}}
}
public class HistoryPopup : Floating {
 readonly Main main;FightSnapshot fight;string message;
 public HistoryPopup(Main m){main=m;PassThrough(true);}
 public void Display(FightSnapshot f,string empty,Rectangle game){fight=f;message=empty;int width=Math.Min(f==null?380:920,game.Width-90),height=f==null?68:Math.Min(252,game.Height/3);Place(new Rectangle(game.X+(game.Width-width)/2,game.Y+18,width,height));if(f!=null)ArtCache.Request(f.Enemy.Select(e=>e.CardId),main.Catalog.Cards.build);Invalidate();}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);using(var font=Theme.Font(12,true)){string title=fight==null?message:main.Catalog.Name(fight.HeroId)+" · last seen turn "+fight.Turn+" · "+Math.Max(0,main.State.Turn-fight.Turn)+" turns ago";TextRenderer.DrawText(e.Graphics,title,font,new Rectangle(12,8,Width-24,30),Theme.Gold,TextFormatFlags.EndEllipsis);}
  if(fight==null)return;int count=fight.Enemy.Count;if(count==0){using(var f=Theme.Font())TextRenderer.DrawText(e.Graphics,"No minions on the recorded board",f,new Point(18,55),Theme.Muted);return;}int tileWidth=Math.Min(126,(Width-20)/7),left=(Width-tileWidth*count)/2;for(int i=0;i<count;i++){var unit=fight.Enemy[i];var image=ArtCache.Get(unit.CardId,main.Catalog.Cards.build);var rect=new Rectangle(left+i*tileWidth,40,tileWidth-4,Height-79);if(image!=null)e.Graphics.DrawImage(image,CardTile.Fit(image,rect));else using(var f=Theme.Font(9))TextRenderer.DrawText(e.Graphics,main.Catalog.Name(unit.CardId),f,rect,Theme.Ink,TextFormatFlags.WordBreak);using(var f=Theme.Font(10,true))TextRenderer.DrawText(e.Graphics,unit.N("ATK")+" / "+Math.Max(0,unit.N("HEALTH")-unit.N("DAMAGE")),f,new Rectangle(rect.X,Height-33,rect.Width,24),Theme.Green,TextFormatFlags.HorizontalCenter);}
 }
}
public class OddsBar : Floating {
 readonly Main main;public OddsBar(Main m){main=m;PassThrough(true);}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);var r=main.Combat.Result;bool current=main.State.CurrentFight!=null&&r.key==main.State.CurrentFight.Key&&(main.State.Phase!="Combat"||main.State.CurrentFight.Turn==main.State.Turn);using(var f=Theme.Font(15,true))using(var small=Theme.Font(8.5f)){
  if(!current||r.status!="estimate"){TextRenderer.DrawText(e.Graphics,current?(r.reason??"Calculating…"):(main.State.Duos?"Waiting for all four Duos warbands": "Odds appear when combat starts"),f,new Rectangle(12,10,Width-24,30),Theme.Muted,TextFormatFlags.HorizontalCenter|TextFormatFlags.EndEllipsis);return;}
  string label=(main.State.Phase=="Recruit"?"PREVIOUS FIGHT · ":"")+(main.State.Duos?"DUOS TEAM · RECONSTRUCTED ESTIMATE":"EXPERIMENTAL · VISIBLE STATE");TextRenderer.DrawText(e.Graphics,label,small,new Rectangle(10,5,Width-20,19),Theme.Gold,TextFormatFlags.HorizontalCenter);
  int stripWidth=Width-32;int winWidth=(int)(stripWidth*r.win/100),drawWidth=(int)(stripWidth*r.draw/100);using(var wb=new SolidBrush(Theme.Green))using(var db=new SolidBrush(Theme.Muted))using(var lb=new SolidBrush(Color.Salmon)){e.Graphics.FillRectangle(wb,16,55,winWidth,3);e.Graphics.FillRectangle(db,16+winWidth,55,drawWidth,3);e.Graphics.FillRectangle(lb,16+winWidth+drawWidth,55,Math.Max(0,stripWidth-winWidth-drawWidth),3);}var vals=new[]{"WIN "+r.win.ToString("0.0")+"%","DRAW "+r.draw.ToString("0.0")+"%","LOSS "+r.loss.ToString("0.0")+"%"};for(int i=0;i<3;i++)TextRenderer.DrawText(e.Graphics,vals[i],f,new Rectangle(i*Width/3,24,Width/3,32),i==0?Theme.Green:i==2?Color.Salmon:Theme.Ink,TextFormatFlags.HorizontalCenter);
  TextRenderer.DrawText(e.Graphics,r.simulations+" simulations · unknown hand/counters can change odds",small,new Rectangle(6,59,Width-12,22),Theme.Muted,TextFormatFlags.HorizontalCenter|TextFormatFlags.EndEllipsis);
 }}
}
public class Overlay : Floating {
 readonly Main main;public bool HasPins {get{return !String.IsNullOrEmpty(Pinned)||main.Settings.PinnedCards.Count>0;}}public bool Interactive;public string Pinned="";public readonly Workbench Tools;public readonly HistoryPopup History;public readonly OddsBar Odds;public readonly BuffCounters Buffs;public readonly DuosHistoryPopup DuosHistory;public readonly CardZoom Zoom;readonly Timer hoverTimer=new Timer();Rectangle game;bool active;public readonly HeroChoices HeroPanel;public readonly SideGuide Guide;public readonly SessionPanel SessionBox;
 public Overlay(Main m){main=m;Text="TavernLens Overlay";Opacity=m.Settings.Opacity;Size=new Size(330,265);Zoom=new CardZoom();Tools=new Workbench(m,Zoom);History=new HistoryPopup(m);DuosHistory=new DuosHistoryPopup(m);Odds=new OddsBar(m);Buffs=new BuffCounters(m);HeroPanel=new HeroChoices(m);Guide=new SideGuide(m,this);Controls.Add(Guide);SessionBox=new SessionPanel(m);SetInteractive(true);hoverTimer.Interval=80;hoverTimer.Tick+=(s,e)=>Hover();hoverTimer.Start();ArtCache.Changed+=ImagesChanged;}
 void ImagesChanged(){if(IsDisposed)return;if(InvokeRequired){if(IsHandleCreated)BeginInvoke(new Action(ImagesChanged));return;}Invalidate();Tools.Invalidate(true);History.Invalidate();Zoom.Invalidate();Guide.ImagesChanged();}
 public void SetInteractive(bool value){Interactive=value;PassThrough(!value);SessionBox.PassThrough(!value);if(!value){Tools.Hide();Zoom.Hide();Guide.Preview.Hide();}Invalidate();}
 public bool Follow(IntPtr target,bool eligible){if(target==IntPtr.Zero||Native.IsIconic(target)||!eligible||!main.Settings.OverlayEnabled){active=false;Hide();HeroPanel.Hide();Tools.Hide();History.Hide();DuosHistory.Hide();Odds.Hide();Buffs.Hide();Zoom.Hide();Guide.Preview.Hide();SessionBox.Hide();return false;}game=Native.ClientBounds(target);if(game.Width<400||game.Height<300){active=false;Hide();HeroPanel.Hide();SessionBox.Hide();Guide.Preview.Hide();Tools.Hide();Odds.Hide();Buffs.Hide();History.Hide();DuosHistory.Hide();Zoom.Hide();return false;}active=true;int width=Math.Min(main.Settings.OverlayWidth,game.Width/2);Place(new Rectangle(game.Right-width-12,game.Top+20,width,Guide.Collapsed?54+(HasPins?150:0):Math.Min(900,game.Height-40)));if(main.Scenes.InLobby||main.Previewing)SessionBox.Follow(game);else SessionBox.Hide();Guide.Sync();HeroPanel.Follow(game);if(main.State.Battlegrounds&&!main.State.Complete&&main.Scenes.Scene!="BACON"){Odds.Place(new Rectangle(game.X+game.Width/2-265,game.Bottom-110,530,87));Odds.Invalidate();}else Odds.Hide();Buffs.Follow(game);Tools.RefreshHistory();Invalidate();return true;}
 public void RefreshLayout(){if(!active)return;int width=Math.Min(main.Settings.OverlayWidth,game.Width/2);Place(new Rectangle(game.Right-width-12,game.Top+20,width,Guide.Collapsed?54+(HasPins?150:0):Math.Min(900,game.Height-40)));}
 public static int HoverSlot(Point cursor,Rectangle b){double logicalWidth=b.Height*4.0/3.0;double left=b.Left+(b.Width-logicalWidth)/2.0;double tile=b.Height*0.69/8.0;double top=b.Top+b.Height*0.15;int slot=(int)Math.Floor((cursor.Y-top)/tile);if(slot<0||slot>7)return -1;double x=left+logicalWidth*0.001*(7-slot);return cursor.X>=x&&cursor.X<=x+tile&&cursor.Y>=top?slot:-1;}
 void Hover(){if(!active||!main.State.Battlegrounds||main.State.Complete||main.Scenes.InLobby||main.Scenes.Loading||Tools.Visible){History.Hide();DuosHistory.Hide();return;}if(main.State.Duos){int team=DuosHistoryPopup.TeamAt(Cursor.Position,game);History.Hide();if(team<0){DuosHistory.Hide();return;}DuosHistory.Display(team,game);return;}DuosHistory.Hide();int slot=HoverSlot(Cursor.Position,game);if(slot<0){History.Hide();DuosHistory.Hide();return;}var hero=main.State.Portrait(slot);if(hero==null){History.Hide();DuosHistory.Hide();return;}FightSnapshot f;main.State.LastFights.TryGetValue(hero.N("PLAYER_ID"),out f);History.Display(f,main.Catalog.Name(hero.CardId)+" · not faced yet",game);}
 protected override void Dispose(bool disposing){if(disposing){ArtCache.Changed-=ImagesChanged;hoverTimer.Stop();hoverTimer.Dispose();Tools.Dispose();History.Dispose();DuosHistory.Dispose();Odds.Dispose();Buffs.Dispose();Zoom.Dispose();Guide.Dispose();SessionBox.Dispose();HeroPanel.Dispose();}base.Dispose(disposing);}
}
}
