using System;
using System.Collections.Generic;
using System.Linq;
namespace TavernLens {
public class TierVisit {public int Turn,Tier;}
public static class OverlayContext {
 public static bool Watched(Main m,string id){var c=m.Catalog.Get(id);return m.Settings.PinnedCards.Contains(m.Catalog.BaseId(id))||(c!=null&&c.tribe.Split('/').Any(t=>m.Settings.PinnedTribes.Contains(t.Trim())))||m.Catalog.BuildMeta.comps.Any(x=>x.name==m.Overlay.Pinned&&x.core.Contains(m.Catalog.BaseId(id)));}
 public static List<RibbonRow> Rows(Main m){var rows=new List<RibbonRow>();var s=m.State;rows.Add(new RibbonRow{Title="Match context",Heading=true});if(!s.Started||s.Complete){rows.Add(new RibbonRow{Title="Waiting for your next match",Caption="No previous rounds are reloaded."});return rows;}var hero=s.Hero;var rank=hero==null?null:m.Catalog.Meta.heroes.FirstOrDefault(h=>h.id==hero.CardId);if(hero!=null)rows.Add(new RibbonRow{Title=m.Catalog.Name(hero.CardId),CardId=hero.CardId,Caption=rank==null?"Hero statistics unavailable":"Global avg "+rank.avg.ToString("0.00")+" · "+rank.games+" games"});rows.Add(new RibbonRow{Title="Turn "+s.Turn+" · "+s.Phase,Caption="Tavern "+(s.Player==null?"unknown":s.Player.N("PLAYER_TECH_LEVEL").ToString())+" · observed state"});
 rows.Add(new RibbonRow{Title="Shop watch",Heading=true});var dummy=s.Entities.Values.FirstOrDefault(e=>e.S("CARDTYPE")=="PLAYER"&&e.N("BACON_DUMMY_PLAYER")>0);var shop=dummy==null?new List<Entity>():s.Board(dummy.N("CONTROLLER"));var matches=s.Phase=="Recruit"?shop.Where(c=>Watched(m,c.CardId)).ToList():new List<Entity>();foreach(var card in matches)rows.Add(new RibbonRow{Title="★ "+m.Catalog.Name(card.CardId),CardId=card.CardId,Caption="Observed shop match · pinned card / tribe / build"});if(matches.Count==0)rows.Add(new RibbonRow{Title="No observed shop matches",Caption="Right-click a minion to watch its card or tribe."});
 rows.Add(new RibbonRow{Title="Board directions",Heading=true});var board=new HashSet<string>(s.Board(s.Controller).Select(e=>m.Catalog.BaseId(e.CardId)));var directions=m.Catalog.BuildMeta.comps.Select(c=>new{Comp=c,Overlap=c.core.Count(id=>board.Contains(id))}).Where(c=>c.Overlap>0).OrderByDescending(c=>c.Overlap).Take(3);foreach(var d in directions){var comp=d.Comp;rows.Add(new RibbonRow{Title=comp.name,Caption=d.Overlap+" / "+comp.core.Count+" core pieces owned · not win odds",Click=()=>m.Overlay.Guide.OpenBuild(comp.name)});}
 rows.Add(new RibbonRow{Title="Hero power / seasonal effects",Heading=true});foreach(var e in s.Entities.Values.Where(e=>!String.IsNullOrEmpty(e.CardId)&&(e.S("ZONE")=="PLAY"||e.S("ZONE")=="SECRET")&&(e.N("CONTROLLER")==s.Controller||e.S("CARDTYPE")=="BATTLEGROUND_ANOMALY")&&(new[]{"HERO_POWER","BATTLEGROUND_TRINKET","BATTLEGROUND_ANOMALY","QUEST","QUEST_REWARD"}.Contains(e.S("CARDTYPE"))||e.N("QUEST")>0))){var card=m.Catalog.Get(e.CardId);rows.Add(new RibbonRow{Title=m.Catalog.Name(e.CardId),CardId=e.CardId,Caption=card==null?"Card details unavailable":card.text});}
 rows.Add(new RibbonRow{Title="Observed counters",Heading=true});if(s.Player!=null)foreach(var pair in new Dictionary<string,string>{{"BACON_BLOODGEMBUFFATKVALUE","Blood Gem attack bonus"},{"BACON_BLOODGEMBUFFHEALTHVALUE","Blood Gem health bonus"},{"BACON_UNDEAD_ATTACK_BONUS","Undead attack bonus"},{"BACON_ETERNAL_KNIGHTS_DEAD_THIS_GAME","Eternal Knights died"},{"NUM_SPELLS_PLAYED_THIS_GAME","Spells cast"},{"BACON_TAVERN_SPELLS_CAST_THIS_GAME","Tavern spells cast"},{"BACON_GOLD_SPENT_THIS_GAME","Gold spent"}})if(s.Player.Tags.ContainsKey(pair.Key))rows.Add(new RibbonRow{Title=pair.Value,Caption=s.Player.N(pair.Key).ToString()+" · observed log value"});rows.Add(new RibbonRow{Title="Opponent tavern history",Heading=true});foreach(var enemy in s.Lobby){int pid=enemy.N("PLAYER_ID");List<TierVisit> visits;s.TierHistory.TryGetValue(pid,out visits);rows.Add(new RibbonRow{Title=m.Catalog.Name(enemy.CardId),Caption=(visits==null?"Tavern changes not observed":String.Join(" · ",visits.Select(t=>"T"+t.Tier+" @ turn "+t.Turn)))+" · "+(enemy.Tags.ContainsKey("PLAYER_TRIPLES")?enemy.N("PLAYER_TRIPLES")+" triples observed":"triples unknown")});}return rows;
 }
}
}
