using System;
using System.Linq;
using System.Drawing;
using System.Windows.Forms;
namespace TavernLens {
public static class RatingTests {
 public static int Run(){int n=0;Action<bool,string> check=(b,s)=>{if(!b)throw new Exception("Rating test: "+s);n++;};check(RatingReader.Parse(new[]{"Ratine","4067","Full Stats"})==4067,"OCR example");check(RatingReader.Parse(new[]{"4,067"})==4067,"thousands separator");check(!RatingReader.Parse(new[]{"4067","200"}).HasValue,"ambiguous digits rejected");check(!RatingReader.Parse(new[]{"loading"}).HasValue,"no invented rating");check(TierOrder.Rank("S")<TierOrder.Rank("A")&&TierOrder.Rank("F")<TierOrder.Rank("unknown"),"tier order");var session=new SessionData();session.ApplyRating(4067);check(session.StartRating==4067&&session.CurrentRating==4067,"baseline");session.Add(new MatchRecord{key="one",placement=2});session.ApplyRating(4150);check(session.Ratings["one"].Delta==83,"win gain");session.Add(new MatchRecord{key="two",placement=8});session.ApplyRating(4075);check(session.Ratings["two"].Delta==-75&&session.CurrentRating-session.StartRating==8,"loss and session total");session.ApplyRating(4078);check(session.Ratings["two"].Delta==-72,"late final rating preserves before value");session.Add(new MatchRecord{key="three"});session.Add(new MatchRecord{key="four"});session.ApplyRating(4200);check(!session.Ratings.ContainsKey("four"),"missing multiple ratings not assigned to one game");var copy=Store.Json().Deserialize<SessionData>(Store.Json().Serialize(session));check(copy.Ratings["one"].Delta==83,"deltas persist");session.Reset();check(session.Ratings.Count==0&&session.Games.Count==0&&session.StartRating==4200,"reset baseline");using(var main=new Main())using(var game=new Form{Bounds=new Rectangle(30,30,1100,800)}){game.Show();main.Settings.OverlayEnabled=true;main.Overlay.Guide.Collapsed=false;main.Overlay.Guide.SelectMode(1);main.Overlay.Follow(game.Handle,true);Application.DoEvents();var list=main.Overlay.Guide.Controls.OfType<RibbonList>().Single();check(list.Rows.First().Heading&&list.Rows.First().Title=="S TIER","S group first in build list");main.Overlay.Guide.BuildTier.SelectedItem="B";check(list.Rows.Where(r=>r.Caption!=null).All(r=>r.Caption.StartsWith("Tier B")),"build tier filter");main.Overlay.Follow(game.Handle,false);game.Close();}return n;}
}
}
