using System;using System.Collections.Generic;using System.Drawing;using System.Drawing.Drawing2D;using System.Drawing.Imaging;using System.IO;using System.Linq;
namespace TavernLens {
public static class RecordedCard {
 static readonly Dictionary<string,Bitmap> icons=new Dictionary<string,Bitmap>();
 public static string ArtId(Entity unit,Catalog catalog){var c=catalog.Get(unit.CardId);if(c!=null&&c.normal>0)return unit.CardId;if(unit.N("PREMIUM")>0){var gold=catalog.Golden(catalog.BaseId(unit.CardId));if(gold!=null)return gold.id;}return unit.CardId;}
 public static int Health(Entity unit){return Math.Max(0,unit.N("HEALTH")-unit.N("DAMAGE"));}
 public static string[] Effects(Entity unit){return new[]{"TAUNT","DIVINE_SHIELD","REBORN","VENOMOUS","POISONOUS","DEATHRATTLE"}.Where(t=>unit.N(t)>0).ToArray();}
 static Bitmap Icon(string name){Bitmap image;if(icons.TryGetValue(name,out image))return image;string file=Path.Combine(Store.Root,"assets","status",name+".png");if(!File.Exists(file))return null;using(var original=new Bitmap(file)){int l=original.Width,t=original.Height,r=-1,b=-1;for(int y=0;y<original.Height;y++)for(int x=0;x<original.Width;x++)if(original.GetPixel(x,y).A>16){l=Math.Min(l,x);t=Math.Min(t,y);r=Math.Max(r,x);b=Math.Max(b,y);}if(r<l)return null;image=original.Clone(Rectangle.FromLTRB(l,t,r+1,b+1),PixelFormat.Format32bppArgb);}icons[name]=image;return image;}
 static RectangleF Box(Rectangle r,float x,float y,float w,float h){return new RectangleF(r.X+r.Width*x,r.Y+r.Height*y,r.Width*w,r.Height*h);}
 public static void Draw(Graphics g,Image art,Rectangle box,Entity unit){var r=CardTile.Fit(art,box);g.InterpolationMode=InterpolationMode.HighQualityBicubic;g.SmoothingMode=SmoothingMode.AntiAlias;g.DrawImage(art,r);
  if(unit.N("DIVINE_SHIELD")>0){var shield=Icon("divine-shield");if(shield!=null)using(var attr=new ImageAttributes()){var matrix=new ColorMatrix();matrix.Matrix33=.42f;attr.SetColorMatrix(matrix);g.DrawImage(shield,Rectangle.Round(Box(r,.24f,.085f,.50f,.425f)),0,0,shield.Width,shield.Height,GraphicsUnit.Pixel,attr);}}
  var effects=Effects(unit);float size=Math.Max(14,r.Width*.19f);float gap=2;for(int i=0;i<effects.Length;i++){string name=effects[i].ToLowerInvariant().Replace('_','-');if(name=="divine-shield")continue;var icon=Icon(name);if(icon==null)continue;int slot=Array.IndexOf(effects.Where(t=>t!="DIVINE_SHIELD").ToArray(),effects[i]);var badge=new RectangleF(r.X+r.Width*.65f,r.Y+r.Height*.17f+slot*(size+gap),size,size);using(var bg=new SolidBrush(Color.FromArgb(205,17,22,29)))g.FillEllipse(bg,badge);float scale=Math.Min((size-4)/icon.Width,(size-4)/icon.Height);g.DrawImage(icon,badge.X+(size-icon.Width*scale)/2,badge.Y+(size-icon.Height*scale)/2,icon.Width*scale,icon.Height*scale);}
  Stat(g,Box(r,.08f,.765f,.255f,.215f),unit.N("ATK"),false,unit.N("DAMAGE")>0);
  Stat(g,Box(r,.752f,.774f,.175f,.202f),Health(unit),true,unit.N("DAMAGE")>0);
 }
 static void Stat(Graphics g,RectangleF r,int value,bool health,bool damaged){string path=Path.Combine(Store.Root,"assets","status","stats.png");if(File.Exists(path)){Bitmap stats;if(!icons.TryGetValue("stats-sheet",out stats)){stats=new Bitmap(path);icons["stats-sheet"]=stats;}Rectangle source=health?new Rectangle(180,192,64,91):new Rectangle(45,192,82,92);g.DrawImage(stats,r,source,GraphicsUnit.Pixel);}else using(var fill=new SolidBrush(health?Color.DarkRed:Color.DarkGoldenrod))g.FillEllipse(fill,r);
  var center=health?new RectangleF(r.X,r.Y+r.Height*.30f,r.Width,r.Height*.66f):new RectangleF(r.X+r.Width*.20f,r.Y+r.Height*.32f,r.Width*.78f,r.Height*.65f);string text=Math.Max(0,value).ToString();float fontSize=center.Height*.91f;using(var family=new FontFamily("Segoe UI"))using(var format=new StringFormat{Alignment=StringAlignment.Center,LineAlignment=StringAlignment.Center})using(var outline=new GraphicsPath()){outline.AddString(text,family,(int)FontStyle.Bold,fontSize,new PointF(0,0),StringFormat.GenericTypographic);var bounds=outline.GetBounds();float scale=Math.Min(1,Math.Min(center.Width/Math.Max(1,bounds.Width),center.Height/Math.Max(1,bounds.Height)));using(var matrix=new Matrix(scale,0,0,scale,center.X+(center.Width-bounds.Width*scale)/2-bounds.X*scale,center.Y+(center.Height-bounds.Height*scale)/2-bounds.Y*scale))outline.Transform(matrix);using(var pen=new Pen(Color.FromArgb(25,20,15),Math.Max(2,r.Height*.065f)){LineJoin=LineJoin.Round})g.DrawPath(pen,outline);using(var brush=new SolidBrush(health&&damaged?Color.FromArgb(255,120,120):Color.White))g.FillPath(brush,outline);}}
}
}
