using System;
using System.IO;
using System.Linq;
using System.Drawing;
using System.Text;
using System.Collections.Generic;
using System.Windows.Forms;
namespace TavernLens {
public static class Tests {
 static int count;static void Check(bool ok,string name){if(!ok)throw new Exception("TEST FAILED: "+name);count++;}
 static string P(string s){return "D 12:00:00.0000000 PowerTaskList.DebugPrintPower() - "+s;}
 public static void Run(string[] args){
  count+=GoldTests.Run();count+=BuffTests.Run();count+=CrownTests.Run();count+=DuosTests.Run();count+=BoardTests.Run();var output=args.Length>0?args[0]:Path.Combine(Store.Root,"test-results.json");
  var s=new MatchState{Stream=@"C:\Logs\Hearthstone_2026_09_11_12_00_00\Power.log"};var records=new List<MatchRecord>();s.OnComplete=records.Add;
  s.Feed("D 12:00:00 GameState.DebugPrintGame() - GameType=GT_BATTLEGROUNDS");
  s.Feed("D 12:00:00 GameState.DebugPrintGame() - PlayerID=1, PlayerName=Local Test");
  foreach(var x in new[]{"CREATE_GAME","GameEntity EntityID=1","tag=TURN value=3","Player EntityID=2 PlayerID=1","tag=CONTROLLER value=1","tag=HERO_ENTITY value=20","Player EntityID=3 PlayerID=9","tag=BACON_DUMMY_PLAYER value=1","FULL_ENTITY - Creating ID=20 CardID=BG20_HERO_202","tag=CARDTYPE value=HERO","tag=PLAYER_ID value=1","tag=HEALTH value=30","tag=CONTROLLER value=1","FULL_ENTITY - Creating ID=50 CardID=BG20_100","tag=CARDTYPE value=MINION","tag=CONTROLLER value=1","tag=ZONE value=PLAY","tag=ATK value=12","tag=HEALTH value=14","tag=ZONE_POSITION value=1"})s.Feed(P(x));
  Check(s.Solo&&s.Controller==1&&s.Turn==2,"Solo / player / turn");Check(s.Board(1).Count==1&&s.Board(1)[0].N("ATK")==12,"Visible board");
  s.Feed("D 12:00:00 GameState.DebugPrintPower() - TAG_CHANGE Entity=50 tag=ATK value=999");Check(s.E(50).N("ATK")==12,"Ignore ahead-of-animation GameState");
  s.Feed(P("TAG_CHANGE Entity=[entityName=Test id=50 zone=PLAY zonePos=1 cardId=BG20_100 player=1] tag=DAMAGE value=3"));Check(s.E(50).N("DAMAGE")==3,"Bracket entity reference");
  s.Feed(P("TAG_CHANGE Entity=Local Test tag=PLAYER_TECH_LEVEL value=4"));Check(s.Player.N("PLAYER_TECH_LEVEL")==4,"Named player reference");
  s.Feed(P("SHOW_ENTITY - Updating Entity=[entityName=Test id=50] CardID=BG36_622"));s.Feed(P("tag=ATK value=15"));Check(s.E(50).CardId=="BG36_622"&&s.E(50).N("ATK")==15,"Entity reveal");
  s.Feed(P("FULL_ENTITY - Updating [entityName=Other id=51 zone=PLAY zonePos=2 cardId=BG20_100 player=1] CardID=BG20_100"));foreach(var x in new[]{"tag=CARDTYPE value=MINION","tag=CONTROLLER value=1","tag=ZONE value=PLAY"})s.Feed(P(x));Check(s.Board(1).Count==2,"PowerTaskList full entity format");
  s.Feed(P("TAG_CHANGE Entity=20 tag=PLAYER_LEADERBOARD_PLACE value=2"));s.Feed(P("TAG_CHANGE Entity=GameEntity tag=STATE value=COMPLETE"));s.Feed(P("TAG_CHANGE Entity=1 tag=STATE value=COMPLETE"));Check(records.Count==1&&records[0].placement==2&&records[0].endedAt.StartsWith("2026-09-11"),"One result with log date");
  s.Feed(P("CREATE_GAME"));Check(s.Entities.Count==0&&!s.Complete,"New game reset");
  var temp=output+".tail";var got=new List<string>();File.WriteAllText(temp,"first\npart",new UTF8Encoding(false));using(var t=new Tail()){t.Open(temp);t.Poll(got.Add,7);t.Poll(got.Add);Check(got.SequenceEqual(new[]{"first"}),"Partial line retained");File.AppendAllText(temp,"ial\n",new UTF8Encoding(false));t.Poll(got.Add);Check(got.SequenceEqual(new[]{"first","partial"}),"Append resumes");File.WriteAllText(temp,"x\n",new UTF8Encoding(false));t.Poll(got.Add);Check(got.Last()=="x","Truncation reset");}File.Delete(temp);
  var catalog=new Catalog();Check(catalog.Cards.cards.Count>1000&&catalog.Meta.heroes.Count>50&&catalog.Meta.comps.Count>5,"Cached feeds loaded");Check(catalog.Meta.comps.All(c=>c.core.Count>0),"Composition core cards loaded");
  string old=catalog.Meta.build;catalog.Meta.build="0";Check(!catalog.MetaFresh,"Mismatched builds flagged");catalog.Meta.build=old;string timestamp=catalog.Meta.updatedAt;catalog.Meta.updatedAt=DateTime.UtcNow.AddDays(-3).ToString("o");Check(!catalog.MetaFresh,"Stale cache flagged");catalog.Meta.updatedAt=timestamp;
  // Verify native overlay geometry and styles against a controlled game-window fixture.
  using(var main=new Main())using(var game=new Form{Text="TavernLens test fixture",Bounds=new Rectangle(80,80,960,680)}){game.Show();Application.DoEvents();main.Settings.OverlayEnabled=true;Check(main.Overlay.Follow(game.Handle,true),"Attach overlay");var bounds=Native.ClientBounds(game.Handle);Check(main.Overlay.Right==bounds.Right-12&&main.Overlay.Top==bounds.Top+20,"Client-area attachment geometry");main.Overlay.SetInteractive(false);Check((Native.GetWindowLong(main.Overlay.Handle,-20)&0x20)!=0,"Click-through style");main.Overlay.SetInteractive(true);Check((Native.GetWindowLong(main.Overlay.Handle,-20)&0x20)==0,"Interactive style");game.Location=new Point(140,110);main.Overlay.Follow(game.Handle,true);Check(main.Overlay.Right==Native.ClientBounds(game.Handle).Right-12,"Follow moved window");main.Overlay.Tools.Tribe.SelectedItem="BEAST";main.Overlay.Tools.Tier.SelectedIndex=3;int expected=main.Catalog.Cards.cards.Count(c=>main.Catalog.Available(c)&&c.pool&&c.tier==3&&(c.tribe.Contains("BEAST")||c.tribe=="ALL"));Check(main.Overlay.Tools.Browser.CardCount==expected&&expected>0,"Beast tier 3 gallery filter");main.Overlay.Tools.Tier.SelectedIndex=1;Check(main.Overlay.Tools.Browser.Controls.OfType<CardTile>().All(c=>c.Card.tier==1),"Tier filter changes shown cards");Check(main.Overlay.Tools.Guide.CardCount>0,"Illustrated build pieces");main.Overlay.Tools.Search.Text="__no_matching_card__";Check(main.Overlay.Tools.Browser.CardCount==0,"Empty search is explicit");main.Overlay.Tools.Search.Clear();Check(main.Overlay.Tools.Browser.CardCount>0,"Clearing search restores tier results");var sample=main.Overlay.Tools.Browser.Controls.OfType<CardTile>().First().Card.name;main.Overlay.Tools.Search.Text=sample;Check(main.Overlay.Tools.Browser.Controls.OfType<CardTile>().All(c=>(c.Card.name+" "+c.Card.text).IndexOf(sample,StringComparison.OrdinalIgnoreCase)>=0),"Search combines with tier and tribe");main.Overlay.Tools.Search.Clear();main.Overlay.Tools.Tabs.SelectedIndex=2;Check(main.Overlay.Tools.Tabs.SelectedIndex==2,"Field guide page navigation");main.Settings.OverlayWidth=300;main.Overlay.Follow(game.Handle,true);Check(main.Overlay.Width==300,"Overlay width setting applied");var rect=new Rectangle(0,0,1920,1080);for(int slot=0;slot<8;slot++)Check(Overlay.HoverSlot(new Point(260,(int)(1080*.15+(slot+.5)*1080*.69/8)),rect)==slot,"Portrait hover geometry "+slot);Check(Overlay.HoverSlot(new Point(960,500),rect)==-1,"Board is outside portrait hover targets");main.Overlay.Follow(game.Handle,false);Check(!main.Overlay.Visible&&!main.Overlay.Tools.Visible&&!main.Overlay.History.Visible&&!main.Overlay.Odds.Visible,"Hide every panel on background");game.Close();main.Overlay.Dispose();}
  count+=SidebarTests.Run();count+=FixTests.Run();count+=RatingTests.Run();count+=AutoTests.Run();object replay=null;
  if(args.Length>1){count+=MidgameTests.Run(args[1]);var log=args[1];var m=new MatchState{Stream=log};FightSnapshot firstSimulation=null;m.OnCombat=f=>{if(firstSimulation==null)firstSimulation=f;};int lines=0,results=0,maxBoard=0,maxTurn=0;m.OnComplete=r=>{results++;Check(r.placement>=1&&r.placement<=8,"Real result placement");};foreach(var line in File.ReadLines(log)){m.Feed(line);lines++;if(lines%2000==0){maxBoard=Math.Max(maxBoard,m.Board(m.Controller).Count);maxTurn=Math.Max(maxTurn,m.Turn);}}Check(results>0&&maxBoard>=7,"Real match log integration");File.WriteAllText(output+".debug.json",Store.Json().Serialize(new{notes=m.SnapshotNotes,fights=m.Fights.Count,turn=m.Turn,mode=m.Mode,controller=m.Controller,players=m.Entities.Values.Where(e=>e.S("CARDTYPE")=="PLAYER").Select(e=>new{e.Id,controller=e.N("CONTROLLER"),pid=e.N("PLAYER_ID"),dummy=e.N("BACON_DUMMY_PLAYER"),hero=e.N("HERO_ENTITY")})}));Check(m.Fights.Count>=10,"Combat snapshots captured");Check(m.Fights.All(f=>f.Enemy.Count<=7&&f.Friendly.Count<=7),"Snapshot board limits");File.WriteAllText(output+".fight.json",Store.Json().Serialize(firstSimulation??m.Fights.First()));File.WriteAllText(output+".late-fight.json",Store.Json().Serialize(m.Fights.Last()));replay=new{lines,results,maxBoard,maxTurn,completed=m.CompletedCount,fights=m.Fights.Count,opponents=m.LastFights.Count};}
  File.WriteAllText(output,Store.Json().Serialize(new{passed=count,replay,at=DateTime.UtcNow.ToString("o")}));
 }
}
}
