const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const {simulate,prepare}=require('./simulate.cjs');
const minion=(id,ctrl,atk,hp)=>({Id:id,CardId:'BG20_100',Tags:{CONTROLLER:String(ctrl),CARDTYPE:'MINION',ZONE:'PLAY',ATK:String(atk),HEALTH:String(hp)}});
function fixture(values){const boards=values.map((v,i)=>({PlayerId:i+1,Board:v?[minion(100+i,i+1,...v)]:[]}));return {Mode:'GT_BATTLEGROUNDS_DUO',Key:'duos-fixture',Stage:'Duos combat opening',Turn:5,GameEntity:1,FriendlyController:1,EnemyController:3,FriendlyFirst:true,EnemyFirst:true,Friendly:boards[0].Board,Enemy:boards[2].Board,FriendlyPartner:boards[1],EnemyPartner:boards[3],All:[{Id:1,Tags:{CARDTYPE:'GAME'}},...boards.flatMap((b,i)=>[{Id:10+i,Tags:{CARDTYPE:'PLAYER',CONTROLLER:String(i+1),HERO_ENTITY:String(20+i),PLAYER_TECH_LEVEL:'2'}},{Id:20+i,CardId:'TB_BaconShop_HERO_PH',Tags:{CARDTYPE:'HERO',CONTROLLER:String(i+1),HEALTH:'30'}},...b.Board])]};}
let f=fixture([[1,1],[100,100],[10,10],[10,10]]),r=simulate(f);assert.equal(r.win,100,'reserve warband carries after first player loses');assert.equal(r.scope,'Duos team estimate');
r=simulate(fixture([[10,10],[10,10],[1,1],[100,100]]));assert.equal(r.loss,100,'enemy reserve cannot be omitted');r=simulate(fixture([[1,1],[1,1],[1,1],[1,1]]));assert.equal(r.draw,100);
f=fixture([[1,1],null,[1,1],null]);r=simulate(f);assert.equal(r.draw,100,'revealed empty reserves count');
let partial=fixture([[1,1],[1,1],[1,1],[1,1]]);delete partial.EnemyPartner;assert.throws(()=>simulate(partial),/four Duos/);partial=fixture([[1,1],[1,1],[1,1],[1,1]]);partial.SnapshotProblem='Unknown reserve';assert.throws(()=>simulate(partial),/Unknown reserve/);
const ref=require('../simulator/node_modules/@firestone-hs/reference-data'),db=new ref.AllCardsService();db.initializeCardsDbFromCards(JSON.parse(fs.readFileSync(path.join(__dirname,'../data/combat-cards.json'))).cards);f=fixture([[1,1],[2,2],[3,3],[4,4]]);f.FriendlyFirst=false;f.EnemyFirst=false;const p=prepare(f,db).input;assert.equal(p.playerBoard.board[0].attack,2);assert.equal(p.opponentBoard.board[0].attack,4);assert.equal(p.playerTeammateBoard.board[0].attack,1);assert.equal(p.opponentTeammateBoard.board[0].attack,3);
process.stdout.write('11 Duos simulator assertions passed: reserve outcomes, ties, entry order and incomplete-state guards.\n');
